### ISSUE TITLE
Running canopy tests in FSI.exe

### ISSUE THREAD

**Issue by HoraceGonzalez** [lefthandedgoat/canopy#114]
Mr. Goat,

Canopy is freaking fantastic! I ran into some trouble, though, while trying to execute some commands in the F# interactive console. For some reason, whenever I try to run:

element "some-selector"

fsi reports the following error:

error FS0074: The type referenced through 'OpenQA.Selenium.IWebElement' is defined in an assembly that is not referenced. You must add a reference to assembly 'WebDriver'.

I'm pretty sure I loaded the reference to WebDriver.dll using the #r "/packages/Selenium.WebDriver.2.35.0/lib/net40/WebDriver.dll" command. 

Have you encountered this issue before?

PS Forgive me. I intended to label this as a question -- not an issue -- but I'm not sure how to add the label.

**Comment by forki** [comment]
I had the same issue (with latest canopy) and I think it was due to order of referencing the dlls. The following works:

    open System
    open System.IO

    //------------------------------------------
    // Step 0. Get the package bootstrap. This is standard F# boiler plate for scripts that also get packages.

    let packagesDir = __SOURCE_DIRECTORY__ + "/script-packages"
    Directory.CreateDirectory(packagesDir)
    Environment.CurrentDirectory <- packagesDir

    if not (File.Exists "paket.exe") then
        let url = "https://github.com/fsprojects/Paket/releases/download/1.2.0/paket.bootstrapper.exe" in use wc = new System.Net.WebClient() in let tmp = Path.GetTempFileName() in wc.DownloadFile(url, tmp); File.Move(tmp,"paket.bootstrapper.exe"); System.Diagnostics.Process.Start("paket.bootstrapper.exe") |> ignore;;

    //------------------------------------------
    // Step 1. Resolve and install the Canopy package and the Chrome web driver
    // You can add any additional packages you like to this step.
    #r "script-packages/paket.exe"


    Paket.Dependencies.Install """
        source https://nuget.org/api/v2
        nuget Canopy
        nuget Selenium.Support
        nuget Selenium.WebDriver.ChromeDriver
    """;;

    //------------------------------------------
    // Step 2. Reference the canopy framework libraries and configure chrome
    #r @"script-packages/packages/Newtonsoft.Json/lib/net40/Newtonsoft.Json.dll"
    #r @"script-packages/packages/Selenium.WebDriver/lib/net40/WebDriver.dll"
    #r @"script-packages/packages/Selenium.Support/lib/net40/WebDriver.Support.dll"
    #r @"script-packages/packages/canopy/lib/canopy.dll"
    #r @"script-packages/packages/SizSelCsZzz/lib/SizSelCsZzz.dll"
    open canopy
    open runner

    canopy.configuration.chromeDir <- Path.Combine(packagesDir, @"packages\Selenium.WebDriver.ChromeDriver\driver")

    //------------------------------------------
    // Step 3. Open Chrome and go to Dynamics NAV page

    let root = "http://localhost:8081/DynamicsNAV80/WebClient/"

    start chrome

    url root

**Comment by lefthandedgoat** [comment]
Thanks @forki !

**Comment by mtnrbq** [comment]
I tried the script, had to add 'nuget Newtonsoft.Json' to the Paket.Dependencies.Install section, and then it was sweet.
Thanks @forki too :)

**Comment by amirrajan** [comment]
This may help too: https://github.com/amirrajan/canopy-repl/blob/master/CanopyRepl.fsx

**Comment by ian-moore** [comment]
@forki's script still works, but as noted above you need to add Newtonsoft.Json AND SizSelCssZzz to the paket dependencies now
