### ISSUE TITLE
Leverage exisitng infrastructure

### ISSUE THREAD

**Issue by shishkin** [lefthandedgoat/canopy#125]
Currently a canopy test is a self-built executable producing its own test report file. Allowing canopy tests to be run from an existing test-runner (e.g. NUnit) will help leverage existing CI infrastructure and standard test report formats.

**Comment by KevM** [comment]
Heh you closed this just as I was thinking about how NUnit integration might work. Did anyone get any where with this?

**Comment by lefthandedgoat** [comment]
You can just use nunit or xunit and not use the canopy.runner stuff.  You lose some nice stuff like WIP mode but it may be worth it.  Personally I never found test runners in Visual studio that enjoyable to use and I prefer command line.  Minority opinion though.

**Comment by KevM** [comment]
I do like the WIP feature but there is the whole org adoption problem I need to worry about. One of the nice things with NUnit is that we can re-run previously failed tests that I am guessing is tricky from a console runner.

**Comment by lefthandedgoat** [comment]
I have support for that, it writes the failed test to a flat file then reads them and runs them first.

https://github.com/lefthandedgoat/canopy/blob/master/tests/basictests/Program.fs#L13

But yah you can use nunit, give it a shot.

**Comment by KevM** [comment]
You are rocking it. I'll give it a try.
