### ISSUE TITLE
Any Suggestion For design 

### ISSUE THREAD

**Issue by unuunc** [lefthandedgoat/canopy#156]
Hi, 
Inviting suggestion for design of framework using canopy, there are multiple ways we can do this , I am listing some of the ways asking for your suggestions 
(Although there is sample project structure available , but still ...)
1.Have a Page objects in a Record Type with each field corresponding to an element. and we can have three types , one with collection of locators, other with data and third one to map
Say Login page
type Element = {Name: string }
type ElementLoc1 = {Name: Element; Loc: string; Action : (canopy.core.op_ComposeLeft)  }
type ElementLoc2 = {Name: Element; Loc: string; Action : (click)  }
type ElementData = {Name: Element; Data:string}
type Login = { userName: ElementLoc; Password: ElementLoc; Submit: ElementLoc2}  

 So now fill up the record type Login and then do Action on each element

2. Other Possibility is to have a Union type of Elements and each Element as its on type
Say 
type LoginElement=
          |Username of ElementLoc1
          |Password of ElementLoc1
          |Submit of ElementLoc2

let UserName = LoginElement.UserName(<pass value for rec. type>)

Just want to check with other guys , which approach you have taken and any pros-cons associated with approaches.

Thanks

**Comment by lefthandedgoat** [comment]
Latest guidance on how to build a test suite can be found in this solution:

https://github.com/lefthandedgoat/canopyStarterKit
