### ISSUE TITLE
IFrame Page load

### ISSUE THREAD

**Issue by dashton82** [lefthandedgoat/canopy#174]
Is there a way to instruct that a certain click action will result in an iframe source being loaded? At present I have a click action that redirects to a page with an iFrame on. That iFrame has script logic in which is constantly retrieving more information which is causing the default page timeout exception to be thrown, would it be possible to have an option to say only to wait for a certain amount of time, or to specify an element which will indicate that the page has loaded correctly?

**Comment by lefthandedgoat** [comment]
I guess I never got around to this.   If you still have problems let me know and I can look into it.  Sorry.
