### ISSUE TITLE
Run tests in parallel

### ISSUE THREAD

**Issue by Buthrakaur** [lefthandedgoat/canopy#175]
Hello, is there any possibility to run canopy tests in parallel? I found suite.IsParallel property in the source code, but it doesn't seem to be used anywhere, so I guess running tests in parallel isn't supported yet?

**Comment by richardjharding** [comment]
Has there been any movement on a way forward? - I've been having great success using Canopy in conjunction with SpecFlow and VSTS but I need to find a way compatible with TFS/VSTS reporting that would allow the tests to run in parallel to cut down the overall execution time

I'm keen to make use of Selenium Grid but running the tests using something like mstest or xunit which can run in parallel and report in trx form seems impossible currently

What are the options in terms of changing the api you've  considered?

**Comment by lefthandedgoat** [comment]
I can provide an alternate API that is parallel friendly.

I *think* I can use this attribute and make it work w/o any api changes, but I have not tested it.

https://msdn.microsoft.com/en-us/library/system.threadstaticattribute(v=vs.110).aspx

I can look into it this weekend if I have time.

**Comment by richardjharding** [comment]
ok sounds promising - happy to help test the change

**Comment by lefthandedgoat** [comment]
I've started down this path and I know a way to do it that is reasonable.

Unfortunately canopy is the first real F# I wrote and it is kind of hacked together, which is making this challenging.

I need to gut some (probably) unused features to make this all easier, so I will need to do major version release, 2.0

Let me do that first, then this change will be easier.  Hopefully it does not take a huge number of hours, but unfortunately I am limited to weekends because of my work/travel schedule, so it may take a bit before it is released.  Sorry!

**Comment by richardjharding** [comment]
no need to apologize! I appreciate its not the day job!  - happy to help where I can

**Comment by oleksiishevchukje** [comment]
@lefthandedgoat Hey, I would like to thank you for everything you are doing. Do you have rough timelines (months/years :) ) for the next major release? 
Anyway, we are looking forward to it (especially, parallel test runs support). Keep up the good work!

**Comment by lefthandedgoat** [comment]
@oleksiishevchukje Sorry but I don't.  Realistically its probably 40 hours of work, the problem is that I travel for work now, so I don't really have much time/energy because of that.

I will try to focus on it and get it done though.

**Comment by haf** [comment]
![parallel-possible](https://user-images.githubusercontent.com/193115/36804981-78411514-1cbc-11e8-81ba-d5b301a9dbb2.PNG)

If I could pass in a context or browser to the selectors, Expecto would automatically parallelise its execution.

**Comment by lefthandedgoat** [comment]
@haf Yes I have to make a secondary API that allows all functions to take a browser so that people can run tests in parallel.  I have done it in my head, just not with my fingers yet.

**Comment by haf** [comment]
Can we release the parallel version?

**Comment by lefthandedgoat** [comment]
@haf  Yes but I need to test it, and create an instanced based parallel version.  I think have 3 APIs is the best, classic, functions with browser argument, instanced w/o browser argument.

I will work to have everything done by Sunday night.

**Comment by lefthandedgoat** [comment]
I've completed canopy 2.0 which has both .net standard 2.0 support and parallel support.

You can download it here: https://www.nuget.org/packages/canopy/2.0.0

You can read the upgrade documentation here: http://lefthandedgoat.github.io/canopy/upgrade1to2.html

**Comment by haf** [comment]
Did you just throw away all my work?

**Comment by lefthandedgoat** [comment]
@haf Sorry, unfortunately I was not able to use your contributions.
