### ISSUE TITLE
Simulate Hover

### ISSUE THREAD

**Issue by navmed** [lefthandedgoat/canopy#177]
My apologies if this is not the right place for this. I could not find any other option - it would be nice to have a forum for Canopy. I'm willing to set this up, if you like. Any way on to my question: I'd like to simulate a mouse hover event. I know this is possible with Selenium, but I could not find any way to do it with canopy or call selenium commands.

**Comment by Navmed** [comment]
Wouldn't this be useful to add to the documentation?

**Comment by lefthandedgoat** [comment]
Pattern matching or the exists function?

**Comment by Navmed** [comment]
The hover feature.

**Comment by lefthandedgoat** [comment]
http://lefthandedgoat.github.io/canopy/actions.html
Done!

**Comment by Navmed** [comment]
Thank you sir.
