### ISSUE TITLE
Ability to pass chromedriver path to BrowserStartMode.ChromeWith...

### ISSUE THREAD

**Issue by flq** [lefthandedgoat/canopy#181]
Hi,
I was wondering if such an _overload_ makes sense. I would rather not put my `chromedriver.exe` to C:\ but a more manageable location. The silly thing is that the path is not part of the options but the ChromeDriver constructor <sup>*</sup>

Would you like this posiiblity, too?

If nobody has time I can also see if I get that in myself - then my hope would be that it lands on NuGet soon, but let?s see how it goes.

<sup>*)Why you would make an arguments object and then leave an argument out is beyond me. :-1: </sup>

**Comment by flq** [comment]
I just found this place in [the source](https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L650) and I am wondering where `chromeDir` comes from?

**Comment by lefthandedgoat** [comment]
https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/configuration.fs#L9

You can change the dirt by doing

canopy.configuration.chromeDir <- @"c:\path\to\chrome\"

**Comment by flq** [comment]
Ah, was really wondering where chromeDir comes from, it's a member of an imported module. My f#reading skills are still lacking. Thanks!
