### ISSUE TITLE
Can't build canopy using FAKE

### ISSUE THREAD

**Issue by kimsk** [lefthandedgoat/canopy#182]
I try to run `build.cmd Build`, but I got the error below:

`The target "Rebuild" does not exist in the project.`

**Comment by KevM** [comment]
I've had this error when I don't have the [F# tools](http://www.microsoft.com/en-us/download/details.aspx?id=44011) installed.

**Comment by lefthandedgoat** [comment]
I just ran it and it worked.  Did you have any luck sorting it out?

**Comment by kimsk** [comment]
Thanks! I did have `F# tools` installed. I'll try to figure out the issue. It's probably my setup.

**Comment by KevM** [comment]
Maybe this [SO answer](http://stackoverflow.com/a/21777168/23820) will help. I seem to remember having a similar problem when switching between VS 2013 and VS 2012.

**Comment by lefthandedgoat** [comment]
Oh Yah, I build against vs 2012 instead of 2013 so that it supports people still using VS 2010.  Maybe you need to install F# 4.3.0 explicitly?

**Comment by amirrajan** [comment]
I've had issues too. It says the "Rebuild" task isn't available.

**Comment by sergey-tihon** [comment]
@kimsk If you change `VisualStudioVersion` from `11.0` to `12.0` it should help
https://github.com/lefthandedgoat/canopy/blob/master/Build.fsx#L86

**Comment by kimsk** [comment]
@sergey-tihon  That works great! My VM only has 2013 installed, so that's probably the issue.

**Comment by sergey-tihon** [comment]
I think that the reason is that the location of `Microsoft.FSharp.Targets` has changed after the version `11.0` https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fsproj#L40-L48
