### ISSUE TITLE
dependency on FSharp.Core not FSharp.Core.3

### ISSUE THREAD

**Issue by ctaggart** [lefthandedgoat/canopy#185]
Please change the NuGet dependency so that Canopy references `FSharp.Core`, not `FSharp.Core.3`.

https://www.nuget.org/packages/canopy/
https://www.nuget.org/packages/FSharp.Core/

**Comment by lefthandedgoat** [comment]
I would but unfortunately it breaks people who are still using VS 2010.

Do you know of a way to build it so it works with vs 2010, 2012 and 2013?

Maybe I need to improve the nuget package to have different dlls for different version of F#?

**Comment by ctaggart** [comment]
`3.0` is there too. Just put a dependency on `FSharp.Core` `3.0.2` package.
http://www.nuget.org/packages/FSharp.Core/3.0.2

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.20
Enjoy!

**Comment by ctaggart** [comment]
You should put a dependency on 3.0.2, but not lock it to that specific version.

**Comment by ctaggart** [comment]
Yeah, here: https://github.com/lefthandedgoat/canopy/blob/master/nuget/canopy.nuspec#L15
change `[3.0.2]` to just `3.0.2`.

**Comment by lefthandedgoat** [comment]
Good catch

https://www.nuget.org/packages/canopy/

**Comment by ctaggart** [comment]
Thank you!
