### ISSUE TITLE
Selenium WebDriver 2.44 not compatible with Firefox 36.

### ISSUE THREAD

**Issue by pottereric** [lefthandedgoat/canopy#187]
There is a known issue with WebDriver 2.44 and Firefox 36. This causes the current version of canopy to fail when connecting to the most recent version of Firefox.

https://code.google.com/p/selenium/issues/detail?id=8399

In my fork, I updated the NuGet packages to WebDriver 2.45 and it resolved the issue.

I submitted a pull request with the updates.

**Comment by lefthandedgoat** [comment]
Thanks! I will get a new nuget package out tonight.

**Comment by lefthandedgoat** [comment]
Thanks!

https://www.nuget.org/packages/canopy/
