### ISSUE TITLE
ability to use already open browser

### ISSUE THREAD

**Issue by ashic** [lefthandedgoat/canopy#188]
No idea if this is possible or not, but it'd be great if there were a way to use an already open browser when running. The start [browsername] at the start is quite slow as it takes a few seconds for a window to launch. Being able to use an existing window would speed this up.

**Comment by lefthandedgoat** [comment]
I don't think what you want to do is possible, read more here: http://stackoverflow.com/questions/26386418/how-to-use-attach-an-existing-browser-using-selenium


Using this code I get these timings:

```
chrome = 1752 ms
firefox = 3087 ms
ie = 2203 ms
```

```
open canopy
let time browser =
    let sw = System.Diagnostics.Stopwatch.StartNew()
    start browser
    sw.Stop()
    printfn "ellapsed time %fms" sw.Elapsed.TotalMilliseconds
[ chrome; firefox; ie; ] |> List.iter time

System.Console.ReadKey()
quit()
```

What kind of times are you seeing?
