### ISSUE TITLE
the after() function should execute after a failed test as well as after a passing test

### ISSUE THREAD

**Issue by dianelaw** [lefthandedgoat/canopy#197]
If failfast is true, it probably doesn't matter if the after function executes, but when failfast is false, it's often more important to execute cleanup steps in the after function when a test fails than when it passes.

**Comment by dianelaw** [comment]
I did it by passing the after function to the function that checks failfast, prints the stack for failing tests, etc. Added the call just after the stack print

Diane Law [11:09 AM]
From run () (in runner .fs):
           with
               | ex when failureMessage <> null && failureMessage = ex.Message -> pass()
               | ex -> fail ex test.Id suite.After
from fail  (also in runner.fs):
let fail (ex : Exception) id after =
   try
       if failFast = ref true 
       then failed <- true        
       failedCount <- failedCount + 1
       contextFailed <- true
       let f = DateTime.Now.ToString("MMM-d_HH-mm-ss-fff")
       let ss = screenshot configuration.failScreenshotPath f
       reporter.fail ex id ss
       after()

Diane Law [11:09 AM]
This would call it regardless of the value of failfast, You could call it conditionally as well.

**Comment by lefthandedgoat** [comment]
thanks I will work on getting something like this in tonight.

**Comment by dianelaw** [comment]
Jeremy just added his version as a pull request too. :-) Thanks, Chris!

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.25

**Comment by lefthandedgoat** [comment]
This has the fix in, 9.25 did not because I forgot to merge the change before building the package.

https://www.nuget.org/packages/canopy/0.9.26
