### ISSUE TITLE
after() function is not called when test fails.

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#200]
The test cleanup function **after()** is not called when a test fails. I think, it should be called regardless.

**Comment by lefthandedgoat** [comment]
I released a new version of canopy this morning which should address this

https://github.com/lefthandedgoat/canopy/issues/197

**Comment by galatrash-at-dnn** [comment]
I've checked the repository but it seems the change #197 is not merged into the master branch.

**Comment by lefthandedgoat** [comment]
You are right, I forgot to merge the pull request, I just did that and when I get home tonight I will do another build and let you know.

**Comment by galatrash-at-dnn** [comment]
Thank you

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.26

That has the change in it.

**Comment by galatrash-at-dnn** [comment]
It would be nicer to have these before/after/once/lastly to work across all the tests and not just the very first context (same as TextFixtureSetup / TextFixtureTeardown / Setup / Teardown in unit test frameworks.

**Comment by lefthandedgoat** [comment]
You want them to not be context specific?

**Comment by galatrash-at-dnn** [comment]
That's what I suggest - across all tests (**once** for the very first test, **lastly** for the very end test, **before**/**after** for all tests)

**Comment by lefthandedgoat** [comment]
Its like that, but its all tests within a context.

If you want to have some nice common code so that you don't have to redefine the same boring once/before/after/lastly for each context I can show you how to do that.  Just take a few minutes.

**Comment by galatrash-at-dnn** [comment]
Also context specific ones could be useful, but these should be defined inside the context itself; not the global level.

**Comment by lefthandedgoat** [comment]
This gist shows:

https://gist.github.com/lefthandedgoat/006f9282e53b9ab29f6e

F# runs the most recently defined version of a function, so by providing a new version of `context` in `canopyExtensions` and opening it after canopy and runner, we get that free default code everywhere.

Does this help accomplish what you want?

**Comment by galatrash-at-dnn** [comment]
Yes, that's wonderful. Thank you.

**Comment by lefthandedgoat** [comment]
You are welcome, enjoy!
