### ISSUE TITLE
Popup windows

### ISSUE THREAD

**Issue by jamesjrg** [lefthandedgoat/canopy#201]
Google tells me that in the Java Selenium API you can call driver.getWindowHandles() to get the handle of a popup window. Does this function exist somewhere in the canopy API as well? If not, is there some other way to deal with popup windows?

Thanks,

**Comment by lefthandedgoat** [comment]
Yes it can handle it.  Sorry it is not documented.

**Comment by jamesjrg** [comment]
Ah, thanks! I did actually notice that method signature but I thought maybe it related only to tabs, not to windows.
