### ISSUE TITLE
Add current URL to error report

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#202]
Adding the current page URL to the error report along with the existing captured image ("canopy-image(iVBORw...)" would add more value to logged information.

needs to be added to this line: ```consoleReporter.fail ex id ss```

**Comment by lefthandedgoat** [comment]
I will add Url, Time information (how long a test took), and stacktrace to the HTML reporter.

**Comment by lefthandedgoat** [comment]
How does this look to you?

![image](https://cloud.githubusercontent.com/assets/725225/8142926/3a7fc13a-1157-11e5-9d73-186ac07d3c1b.png)

**Comment by lefthandedgoat** [comment]
And because I realized that I am not sure if you are talking about the console out put or the html out put, here it is in the console 

![image](https://cloud.githubusercontent.com/assets/725225/8142946/618440fc-1158-11e5-8f4e-d041724723f7.png)

**Comment by galatrash-at-dnn** [comment]
Thank you. Are you going to support the new Selenium release 2.46.0 ?

**Comment by galatrash-at-dnn** [comment]
BTW, I don't see the changes published to NuGet or GITHUB  :^)

**Comment by lefthandedgoat** [comment]
I didn't make the changes yet, I was making sure this was addressing your problem =).

And yes I can update to latest Selenium too.

**Comment by galatrash-at-dnn** [comment]
Yes, this is what I was looking for. Thanks or your prompt actions.

**Comment by lefthandedgoat** [comment]
Released now, enjoy!

**Comment by lefthandedgoat** [comment]
I broke the reporter link with 0.9.27 and I am fixing it now.  I have removed that listing from nuget and am working on a fix now.

**Comment by lefthandedgoat** [comment]
Fixed in 0.9.28 and published.  Sorry!
