### ISSUE TITLE
== Operator issue when passing IWebElement

### ISSUE THREAD

**Issue by arsdata** [lefthandedgoat/canopy#208]
While this command is successful
    **".navbar-brand" == "AUP"**
Can anyone tell me why this line:
    **(element ".navbar-brand") == "AUP"**

results in this error?
Error:
Can't check equality on OpenQA.Selenium.Remote.RemoteWebElement because it is not a string or alert
Url: http://myurl.com
Stack:
   at canopy.core.op_EqualsEquals[a](a item, String value) in C:\projects\canopy
\src\canopy\canopy.fs:line 437
   at Program.clo@24.Invoke(Unit _arg1) in C:\Users\jj06848\Projects\AUPE2ETest\
AUPE2ETest\CanopyTest\Program.fs:line 28
   at canopy.runner.runtest$cont@93(suite suite, Test test, Unit unitVar) in C:\
projects\canopy\src\canopy\runner.fs:line 102

according to the docs both of these should be successful. I have several other places in my test where I attempt to pass an IWebElement into a assertion but all seem to have the same error. For example:

    let bidHistoryResults = (elements ".table-striped")
    let bidHistoryRows = bidHistoryResults.[2] |> elementsWithin "tr"
    let firstRow = bidHistoryRows.[1] |> elementsWithin "td"
    let secondRow = bidHistoryRows.[2] |> elementsWithin "td"
    firstRow.[6] == "$15.93"

**Comment by lefthandedgoat** [comment]
You are right. The documentation shows it but the code does not allow it.
I will need to do a fix when I get back into town.  Sorry for the
inconvenience.

**Comment by arsdata** [comment]
No problem, is there a work around that I can use in the interim? If not I'll just add id tags for now. Thanks for the quick answer.

**Comment by lefthandedgoat** [comment]
It's not a workaround and will probably work better to use a css/jQuery
selector to do this .  Something like ".table-striped:eq(1) tr:eq(0)
td:eq(5)" == "$15.93" should work. I may be off by one on the eq indexes.
This will allow the == operator to retry the check if it initially fails
like if the grid hasn't loaded via Ajax.  Hope this helps. If not please
let me know.

**Comment by arsdata** [comment]
Perfect...thanks for the push in the right direction.

**Comment by lefthandedgoat** [comment]
Is everything working ok for you?  I think I will adjust the documentation because direct equality checking on IWebElement will open up for brittle tests.  You would lose the retry-ability that is baked into canopy.

**Comment by arsdata** [comment]
Yes, Chris everything seems to be working well. I just have a learning curve related to CSS/JQuery selectors. Either that or I have to get our developers more consistent in adding id’s to elements ☺

**Comment by lefthandedgoat** [comment]
Ok cool, here are some good resources for that

CSS: http://www.cheetyr.com/css-selectors
CSS + Jquery: http://oscarotero.com/jquery/
XPath: http://www.w3schools.com/xsl/xpath_intro.asp

**Comment by lefthandedgoat** [comment]
updated documentation, thanks!
