### ISSUE TITLE
Fail screenshots are taken too late

### ISSUE THREAD

**Issue by edmellum** [lefthandedgoat/canopy#209]
I'm working with a test suite where we login to a web app in our `before` and logout in `after`. When a test fails we're seeing that the screenshot that gets taken is taken after the `after` function is run, not right after the test failed. That means every single screenshot we get after a test has failed is of the login screen as we have just logged out.

After a little exploratory debugging the problem seems to be [here](https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/runner.fs#L103). The `finally` block is run before the [pattern match](https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/runner.fs#L108) that runs `fail` which takes the screenshot.

I wrote a little user story too, in case my explanation above wasn't clear enough. :smiley: 

As a tester. When a test fails I want a screenshot of the condition the browser is in at the closest possible moment to the test failing. So that I can debug the failing test.

**Comment by lefthandedgoat** [comment]
Thank you for filling the issue.  I will look at it as soon as I can.  Hopefully tonight.

**Comment by lefthandedgoat** [comment]
This is fixed and available https://www.nuget.org/packages/canopy/0.9.31

Let me know if you have any other issues.  Thanks for opening this issue!

**Comment by edmellum** [comment]
Wow great work! :smile:

Hopefully I'll get confident enough with the project that I'll submit a PR right away myself next time.
