### ISSUE TITLE
The message in the bottom right corner for puts and describe can be obstructive

### ISSUE THREAD

**Issue by lefthandedgoat** [lefthandedgoat/canopy#213]
Make it configureable

**Comment by amirrajan** [comment]
Is it really being used?

**Comment by lefthandedgoat** [comment]
It is useful when a test fails to have the message there.  You added it ;p

**Comment by amirrajan** [comment]
I know XD, just was wondering if it was still helpful

**Comment by lefthandedgoat** [comment]
Yep it is helpful except for the 1% of the time it gets in the way.

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/
