### ISSUE TITLE
How to use "many" and set proper test name at the same time?

### ISSUE THREAD

**Issue by mkulava** [lefthandedgoat/canopy#219]
Hello,

I really like the feature "many" (which runs unstable tests multiple times), but didn't find the way to set the test name and "many" at the same time

many 3 "Test something, do something" &&& fun _ ->
//test body

**Comment by lefthandedgoat** [comment]
Unfortunately there is not one.
```
let many count f = 
    let lastSuite = incrementLastTestSuite()
    [1 .. count] |> List.iter (fun _ -> lastSuite.Manys <- Test(null, f, lastSuite.TotalTestsCount)::lastSuite.Manys)
```
The current many uses `incrementLastTestSuite` which is private so you can't quickly add your own.

If you like I can add it for you and do a new nuget build.

**Comment by mkulava** [comment]
Yes please, that would be great.

**Comment by lefthandedgoat** [comment]
You can download the latest page here once its been indexed by nuget!

https://www.nuget.org/packages/canopy/0.9.40

```
nmany 5 "awesome test" (fun _ ->
    url "http://www.google.com"
)
```

**Comment by mkulava** [comment]
Thanks a lot! Works great so far

**Comment by lefthandedgoat** [comment]
Anytime, enjoy!
