### ISSUE TITLE
 Expose more information about test execution in the runner

### ISSUE THREAD

**Issue by mkulava** [lefthandedgoat/canopy#220]
Hi,

Since we have started running our UI tests on CI we are facing the lack of information on failed tests (some times screenshots do not give full picture of what has happened). So we are considering adding video capturing of the screen while executing tests. I plan to add the recorder calls in "before" and "after" functions to record each test in sepparate file - in case if the test is passed we are going to delete the file in "after" function, so at the end we get only the video files with the failed tests.

We need a possibility to get the next test's description (the one that will be executed after the current "before" call) and get the previos test status (passed or failed) in the "after" function. Any ideas how this can be done better?

P.S. this is a question, but I didn't figured out how to add proper label to my post.

**Comment by lefthandedgoat** [comment]
I can't think of any quick work around for you to use right now.  Let me think a little more on a good solution to add to the runner.

**Comment by mkulava** [comment]
Sure, no rush.

**Comment by lefthandedgoat** [comment]
I started to think about this and you don't actually know if a test has passed when ```after``` is run.  Also knowing what test is next is going to bit of a pain.

How about I just provide two hooks.  One that runs when a test passes, one that runs when a test fails.  Then you can start recording in ```before```, then in ```pass``` you can delete the file, and in ```fail``` you can move it to a safe location, or name it so it won't be deleted or whatever works best for you.

Another option would for you to use the IReporter interface and write your own reporter wrapper on an existing reporter.  It has all the hooks for Test start, pass, fail, skip, todo, test end, context start and end.
You can see all the reporter functions here https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs
Consolereporter is the stock reporter, and LiveHtmlReporter provides its own custom functionality and still wraps a Consolerporter.  

I think the Reporter option will be the most robust, but if it doesn't fulfill you needs I can keep thinking.

**Comment by mkulava** [comment]
Own reporter option sounds good, I will try to make it work. Thanks for a good idea.
