### ISSUE TITLE
Adding more FF browser creation options

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#223]
If possible, please add a new browser creation option for FireFox as:

``| FirefoxWithPathAndTimeSpan(path, timespan) -> new FirefoxDriver(Firefox.FirefoxBinary(path), Firefox.FirefoxProfile(), timespan) :> IWebDriver``

**Comment by lefthandedgoat** [comment]
Yep I will try to get a build out tonight!

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.41

I built this on a windows 10 machine that I just setup.  Please let me know if you have any problems.

**Comment by galatrash-at-dnn** [comment]
It is working fine. Thank you.
