### ISSUE TITLE
How to run Chrome from Visual Studio and window-less-browser from CI.

### ISSUE THREAD

**Issue by Thorium** [lefthandedgoat/canopy#227]
Q: How to run Chrome from Visual Studio and PhantomJS (window-less-browser) from continuous integration / build servers?

A: Like this:

    //...
    if System.Diagnostics.Debugger.IsAttached then
        start chrome
    else
        start phantomJS
    
    //...
    "Some tests" &&& fun _ ->
        ()//...
    run()
    //...
    
    if System.Diagnostics.Debugger.IsAttached then
        printfn "press [enter] to exit"
        System.Console.ReadLine() |> ignore

**Comment by JeremyBellows** [comment]
If you wanted to extend the functionality to add multiple sources then another option is to pass arguments via command line and parse that into a discriminated union

To run it, the command would look like:

```C:\canopyTests.exe -Source console```
or
```C:\canopyTests.exe -Source buildServer```

Then use some fsharp library to parse the passed arguments. (like http://nessos.github.io/Argu/)

```
type Source = 
| Console
| BuildServer

let source = processArgs args

match source with
| Console -> start chrome
| BuildServer -> start phantomJS
| _ -> start chrome //Default for safety
```

**Comment by Thorium** [comment]
Thanks!

This wasn't actually an issue, just info.
