### ISSUE TITLE
F# Canopy Select or Dropdown with Option Group

### ISSUE THREAD

**Issue by chongo2002** [lefthandedgoat/canopy#240]
How do you select an option or set the value in a select list that has option groups?

This method does not work: How to change a dropdown in an F# Canopy UI Testing Script

sample code:

```
<!DOCTYPE html>
<html>
<body>

<select id="test-select">
  <optgroup label="Swedish Cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
  </optgroup>
  <optgroup label="German Cars">
    <option value="mercedes">Mercedes</option>
    <option value="audi">Audi</option>
  </optgroup>
</select>

</body>
</html>
```

Canopy Test:

```
open canopy
open runner
open Helpers

    let all() =
    context "OptGroup Tests"

    let page = ""

    ntest ("Testing page " + page) (fun _ ->
        let mUrl = testpage.html
        url mUrl

        "#test-select" << "Audi"
    )
```

Note I am trying to select by text value, not option value, although I have tried both and neither work.

Issue is on StackOverflow: [http://stackoverflow.com/questions/35798661/f-canopy-select-or-dropdown-with-option-group](url)

**Comment by amirrajan** [comment]
What I've find myself doing these days is explicitly adding marker attributes to all elements I'd want to interact with. This of course is only viable if you can change the source code. 

For this example I'd add a marker class to each `option`, for example: `data-uia-car="Audi"`. Then I can interact with it via canopy by typing `click "[data-uia-car='Audi']"`.

Without changing the markup, you could probably do `click "[value='Audi']"` and it should work.

That being said. I think it'd be cool if canopy could just traverse these kind of `optgroup` structures and "just work". /cc @lefthandedgoat

**Comment by lefthandedgoat** [comment]
Yep looks like an oversite on my part.  I will work to get this fixed soon.  Wednesday probably.

Thanks!

**Comment by lefthandedgoat** [comment]
You can download this now!  No changes needed on your side.  Should 'just work'.

https://www.nuget.org/packages/canopy/0.9.46
