### ISSUE TITLE
trouble starting browsers

### ISSUE THREAD

**Issue by jackfoxy** [lefthandedgoat/canopy#249]
Haven't tried canopy in a long time, and just tried doing the "getting started" tutorial in fsi

    #r @"packages\Selenium.WebDriver.2.52.0\lib\net40\WebDriver.dll"
    #r @"packages\Selenium.Support.2.45.0\lib\net40\WebDriver.Support.dll"
    #r @"packages\canopy.0.9.47\lib\canopy.dll"
    #load "Core.fs"
    open canopy
    open runner
    open System
    start ie

Binding session to 'D:\BitSync\GitRepos\Dojo-Canopy-2048\Dojo\Canopy2048\packages\Selenium.WebDriver.2.52.0\lib\net40\WebDriver.dll'...
> OpenQA.Selenium.DriverServiceNotFoundException: The file c:\IEDriverServer.exe does not exist. The driver can be downloaded at http://selenium-release.storage.googleapis.com/index.html
   at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
   at OpenQA.Selenium.IE.InternetExplorerDriverService..ctor(String executablePath, String executableFileName, Int32 port)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(String internetExplorerDriverServerDirectory, InternetExplorerOptions options)
   at canopy.core.start(BrowserStartMode b) in C:\projects\canopy\src\canopy\canopy.fs:line 687

trying to start chrome

    start chrome

OpenQA.Selenium.DriverServiceNotFoundException: The file c:\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html
   at OpenQA.Selenium.DriverService..ctor(String servicePath, Int32 port, String driverServiceExecutableName, Uri driverServiceDownloadUrl)
   at OpenQA.Selenium.Chrome.ChromeDriverService..ctor(String executablePath, String executableFileName, Int32 port)
   at OpenQA.Selenium.Chrome.ChromeDriver..ctor(String chromeDriverDirectory, ChromeOptions options)
   at canopy.core.start(BrowserStartMode b) in C:\projects\canopy\src\canopy\canopy.fs:line 694

**Comment by lefthandedgoat** [comment]
Jack!

Yah both IE and Chrome require a 'driver'.  Firefox is simpler and should work no problem.

You need to download the driver from here:

Chrome: http://chromedriver.storage.googleapis.com/index.html?path=2.21/

IE: http://www.seleniumhq.org/download/ in the `The Internet Explorer Driver Server` section.

You can drop them at root `c:\` and if you aren't comfy with that you can put them in any folder you like, and set `canopy.configuration.chromeDir` or `canopy.configuration.ieDir` to the path you want.

I generally put the in my solution and set them to copy to my bin directory, then set the `chromeDir` to the executing assembly folder with this code `canopy.configuration.chromeDir <-System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location)`

**Comment by jackfoxy** [comment]
Thanks! The drivers would be a good thing to put prominently on the getting started page. I think Firefox has become less popular. For instance it is not even installed on the machine I'm currently working on.

**Comment by amirrajan** [comment]
@jackfoxy If you are trying to use just `fsx` files, you may want to look [canopy-repl](https://github.com/amirrajan/canopy-repl/blob/master/CanopyRepl.fsx) for a good starting point.

**Comment by jackfoxy** [comment]
@amirrajan Past my original issue, but thanks for the link. This looks useful, but I see the readme note 

    Works on OSX only

which does not work for me. Since it does not, can you tell me which lib the Chrome object lives in? I still may find that useful in a Windows environment.

**Comment by amirrajan** [comment]
Well with Win 10 supporting bash now, it should work :-). It should be straight forward to make it work for Windows the `#r` and `#load` paths just need to be updated.

**Comment by jackfoxy** [comment]
I'll look into it. Thanks
