### ISSUE TITLE
Multiple Dropdowns on Page

### ISSUE THREAD

**Issue by JustinJohnWilliams** [lefthandedgoat/canopy#253]
I think https://github.com/lefthandedgoat/canopy/commit/47d8cad3a3f4bbfd044e31230232ed598173d647 may have broken our test suite on pages that have multiple drop downs.

HTML for repro:
```HTML
<!DOCTYPE html>
<html>
<body>

<select id="test-select">
    <option value="r">Red</option>
    <option value="g">Green</option>
    <option value="b">Blue</option>
</select>
<br />
<select id="test-select2">
    <option value="r">Red</option>
    <option value="g">Green</option>
    <option value="b">Blue</option>
</select>

</body>
</html>
```

Canopy Tests for Repro:

```fsharp
"multiple drop downs" &&& fun _ ->
    url "testpage.html"
    "#test-select" << "g"
    "#test-select2" << "b"
    "#test-select" == "Green"
    "#test-select2" == "Blue"
```

BUG: when selecting "b" on the second dropdown list, it's actually changing the first dropdown list

**Comment by lefthandedgoat** [comment]
Thanks will get it fixed this weekend

**Comment by lefthandedgoat** [comment]
Sorry about that!

You can find the fixed version of canopy here https://www.nuget.org/packages/canopy/0.9.50

Thanks for the bug report and repo steps!!

**Comment by JustinJohnWilliams** [comment]
Thank you for the quick update! verified on our end.
