### ISSUE TITLE
Canopy issues

### ISSUE THREAD

**Issue by Thorium** [lefthandedgoat/canopy#258]
I'm trying to use canopy with Foundation 5, React.js, SignalR, and Rx-js. I found a couple of issues, but I don't know is it about canopy or is it just that I can't find documentation.

1. How can I clear default value and write to javascript `prompt("write something")` dialog? I notice that I can close it via `acceptAlert()`. Should I try some `press OpenQA.Selenium.Keys.Backspace` combination?
2. How can I slide jQuery-UI slider?
3. I can't follow a link that is inside ReactJS-component and Foundation 5 dropdown. I guess I had to wait until everything is rendered but waitFor does not work as I expect. If I do as an example code, `waitFor (fun _ -> (element "#pageLoaded").Displayed)` it will fail:

```
OpenQA.Selenium.InvalidSelectorException: invalid selector: Unable to locate an element with the xpath expression #pageLoaded because of the following error:
SyntaxError: Failed to execute 'evaluate' on 'Document': The string '#pageLoaded' is not a valid XPath expression.
  (Session info: chrome=50.0.2661.87)
  (Driver info: chromedriver=2.9.248315,platform=Windows NT 6.3 x86_64)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
```

Actually it will fail with the same exception if I try to examine React.js component properties like
 `true === element("#mypanel").Displayed`

This waitFor2 is not any better, but it takes an int of timeout but in what unit?

**Comment by lefthandedgoat** [comment]
For #3 just try `displayed "#pageLoad"`

#2 do this (and I can add this canopy if you want)

```
let dragX cssSelectorA pixels = 
    wait elementTimeout (fun _ ->
        let a = element cssSelectorA
        (new Actions(browser)).DragAndDropToOffset(a, pixels, 0).Perform()
        true)
```
```
"drag x" &&& fun _ -> 
    url "https://jqueryui.com/slider/"
    dragX ".ui-slider-handle" 100
```

For #1 (I can add this to canopy also)

```
let writeToAlert text = 
    wait compareTimeout (fun _ ->
        let alert = browser.SwitchTo().Alert()
        alert.SendKeys(text)
        alert.Accept()
        true)
```

```
"Write to alert" &&& fun _ ->
    url "http://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_prompt"
    click "button[onclick='myFunction()']"
    sleep 2.0 //so you can see the alert
    writeToAlert "hi from canopy"
```

**Comment by lefthandedgoat** [comment]
Just realized that this is probably using the internal 'wait' function, you may have to switch to waitFor.

**Comment by Thorium** [comment]
1. For some reason this didn't work for me, but it's not important.
2. Thanks! But the silder can be modifying by the internet browser width. So absolute pixels are not nice. I ended up with the following code:

```
/// drag ".range-slider" or ".ui-slider" to zero-to-one based percentage position
let dragJQuerySlider cssSelectorSlider positionPercentage = 
    waitFor (fun _ ->
        let slider = element cssSelectorSlider
        let handle = "span" |> OpenQA.Selenium.By.TagName |> slider.FindElement
        let pixels = 
            let target = (decimal slider.Size.Width) * positionPercentage
            let halfHandleSize = (decimal handle.Size.Width)/2m |> int
            (int target) + slider.Location.X - handle.Location.X - halfHandleSize 
        let act = OpenQA.Selenium.Interactions.Actions browser
        act.DragAndDropToOffset(handle, pixels, 0).Perform()
        true)

```

```
"drag x" &&& fun _ -> 
    url "https://jqueryui.com/slider/"
    dragX ".ui-slider" 0.5m
```

3. Thanks! Seems like I wasn't too careful with the jQuery query-selector-strings.

**Comment by lefthandedgoat** [comment]
Awesome! glad you got it working
