### ISSUE TITLE
Html Reporter templates do not load correctly

### ISSUE THREAD

**Issue by bornatow** [lefthandedgoat/canopy#262]
Hi,

I tried using the following templates for HTML reporting, and they do not work anymore. Yesterday I was able to use them without any problem. I am using canopy 52.
https://lefthandedgoat.github.io/canopy/reporttemplate.html
and
https://lefthandedgoat.github.io/canopy/reporttemplatep.html

**Comment by lefthandedgoat** [comment]
Looks like a problem with mix mode http/https, I will fix it

**Comment by lefthandedgoat** [comment]
Fix is pushed and worked for me.  Let me know if you have any issues.  It should 'just work'!

**Comment by bornatow** [comment]
Super fast, mate! It is fixed now.
