### ISSUE TITLE
Add notContains support

### ISSUE THREAD

**Issue by nvtaveras** [lefthandedgoat/canopy#263]
I was using the library the other day and wrote a test that should fail if the app ever showed a div containing an error class (it could happen on random occasions).

I did a temporary work around by wrapping the contains method into a try/catch, but figured it would be good to have a notContains assertion method (as we currently have one for notDisplayed).

Thoughts? I'll be more than happy to work on it :)

**Comment by lefthandedgoat** [comment]
Yah you can add one if you like and I can do a new build.

Probably the best solution is to copy/paste/modify the existing contains

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L468-L470

**Comment by lefthandedgoat** [comment]
I will do a build tonight and include this feature.

**Comment by lefthandedgoat** [comment]
You can download this now here: https://www.nuget.org/packages/canopy/0.9.54
