### ISSUE TITLE
Style Vs. Function; and waitFor

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#266]
I have the following code in the latter part of my test cases:

```
// Enter page 4 of Application data and submit application
click "#label-firstOwner-acceptance"
"#firstOwner-ssn" << getRandomSsnNum
click "#nextButton"
**let confirmationNumber = read "#confirmation-number"**         // Read back confirmation number 
sleep 30
// Queries SQL db for salesforce oppertunity id, has delay starting with "#nextButton", see "sleep 30"
**let getSfOppertunityID = getOppertunityID (confirmationNumber)
let sfOppertunityID = getSfOppertunityID.Substring(0, 15)**
        
url sfroot                    // Navigate to Salesforce login page
sflogin 

// Build and navigate to oppertunity, using the ID
let newOppertunity = "https://cs2.salesforce.com/"+ getSfOppertunityID   
url newOppertunity

// Click on the "Notes & Attachments" link 
click ("#" + sfOppertunityID + "_RelatedNoteList_link .listTitle") 
// Click on "Estimated Quote Details"               
click ".noStandardTab .last th+ .dataCell a" 
// Validate the expected payment calc. (Maint:The $$ value is tied to the pricing obj)                                    
contains "Estimated Payment: $1041/MONTH" (read "tr:nth-child(5) .data2Col") 
```

Question 1: Should the "let definitions be moved to the top of the file outside the test cases, so not to 
litter up the script.

Question 2: My experience writing functions in F# is limited. I haven't used lambda expressions. Is there a better way  to write up my let statements into a function?

Question 3: getSfOppertunityID  often fails because the delay, as it is not reliable. I Can't seem to wrap this using the "waitFor"  as I get the compile error "expression expects a bool, but here has type string.

**Comment by lefthandedgoat** [comment]
#1, you don't need to move your let definitions, because things in F# are immutable by default, you dont have separate variable definitions and assignments, they go together.  How you have things is fine.

#2  Your let statements look fine to me.

#3 Yes waitFor requires last last line of the function to be a bool.  What does getOppertunityID (confirmationNumber) call return if the value is not in the database?  If it returns an empty string you could do something like this

```
let confirmationNumber = read "#confirmation-number" // Read back confirmation number 
waitFor (fun _ ->  getOppertunityID confirmationNumber <> "")

let getSfOppertunityID = getOppertunityID (confirmationNumber)
let sfOppertunityID = getSfOppertunityID.Substring(0, 15)
```
That will run the waitFor until your query returns a non empty string value, then the next line will actually query it.

Hope this helps.

**Comment by sprice9161** [comment]
#3 There are 2 apps in play here. The first on is our online loan application app, and it creates a unique "confirmation#. The second is Salesforce (we customize to work as our engine) which creates an entity in both the Salesforce DB and SQL DB.  The getOppertunityID (confirmationNumber) returns the ID (string), however there is a minimum 6 sec delay in the ID creation. Since the delay is becoming a moving target (currently at 30 sec), I need to use a wait for of some kind. I'll take a closer look at the code you sent.

Thank you!

**Comment by sprice9161** [comment]
Just ran my test successfully to completion. The "waitFor" statement worked great. I'll run it a bit more.

Thanks Again!

**Comment by lefthandedgoat** [comment]
Awesome, glad it worked!

**Comment by sprice9161** [comment]
This is not explainable but what was once working is no longer working. No edits, no changes...I discovered this after reusing the code in another canopy test file. I Then reran the original and I'm getting the same failure.

It appears from stepping through the script, that "waitFor" may not be waiting. Most of the time stepping through will pass and other times it will fail.

I added a second "waitFor" statement for of the functions that I'm using, and I'm getting the same unstable results. 

I know that the first wait for should be at least a few second up to 30 sec,  but it executes in the milliseconds every time. So I don't really know if its doing anything.
 
![nullobject passing](https://cloud.githubusercontent.com/assets/18660936/16233949/fca06824-379d-11e6-8b5f-481c3a173432.JPG)
 

Attached is a code snippet, containing the failure and the error message
![nullobject](https://cloud.githubusercontent.com/assets/18660936/16232500/c6626e56-3798-11e6-9949-2c425680d423.JPG)

**Comment by lefthandedgoat** [comment]
Ah, its coming back null instead of ""

change line 79 from

```
waitFor (fun _ -> getOppertunityId confirmationNumber <> "")
```

to something like

```
waitFor (fun _ -> 
  getOppertunityId confirmationNumber
  |> System.String.IsNullOrWhiteSpace
  |> not)
```

That will be more robust.

**Comment by sprice9161** [comment]
Looks like its timing out now. I attempted to implement the "compareTimeout" but that didn't help. See attachment.
![nullobject_stillfails](https://cloud.githubusercontent.com/assets/18660936/16240403/260e09e6-37b7-11e6-80bf-23926141ee26.JPG)

**Comment by sprice9161** [comment]
Seems to be passing now. ran it several time, I'll keep an eye on it. The only changes that might be note worthy are:
Commented "compareTimeout", which didn't seem to do anything prior
Removed "()" from "getOppertunityID" function and function call

**Comment by lefthandedgoat** [comment]
You need to adjust your compare timeout to be ~30 seconds for it work for your case.  It is set to 10 by defualt.  If you look at the error message in your screenshot it gives you a hint

```
compareTimeout <- 35.0
```
Is the syntax

**Comment by sprice9161** [comment]
Yes and if you look at the commented line, I had previously set it to "compareTimeout <- 30.0".
Did you see something for "35" in the error message? I don't see that.

**Comment by lefthandedgoat** [comment]
Sorry I did not see the commented out line.  I was just reading the error message in the screenshot and explaining what it meant.

I chose 35 because you had said around 30 seconds, so I threw in some extra padding.

When it is work with that line commented out, it must be happening faster than 10 seconds.  Sorry for the confusion.
