### ISSUE TITLE
Firefox 47: make sure the webdriver works 

### ISSUE THREAD

**Issue by lefthandedgoat** [lefthandedgoat/canopy#270]
From @ataylorm 

https://github.com/SeleniumHQ/selenium/issues/2110
 
https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver

**Comment by lefthandedgoat** [comment]
After some reading this seems to be a bigger problem.

Best course of action is to revert to FF 46 until the situation improves.

http://stackoverflow.com/questions/37693106/selenium-2-53-not-working-on-firefox-47

**Comment by mbowman8** [comment]
Firefox 47.0.1 and Selenium Webdriver 2.53.1 has been released. Would you please update Canopy to be compatible with this version?

**Comment by lefthandedgoat** [comment]
Yep!
