### ISSUE TITLE
Right Click Support [feature request]

### ISSUE THREAD

**Issue by mreishus** [lefthandedgoat/canopy#273]
I'm able to get a right click working via:

```
open OpenQA.Selenium.Interaction
(new Actions(browser)).ContextClick(element "#myselector").Perform() |> ignore
```

But it'd be nice to just `contextClick "#myselector"` :smile:

**Comment by lefthandedgoat** [comment]
Yah I can get a build done later today with that.

**Comment by lefthandedgoat** [comment]
https://www.nuget.org/packages/canopy/0.9.56

You can see an example in the tests here: 

https://github.com/lefthandedgoat/canopy/commit/33384df7b1f8846c418460f08f7a3e1a8decb261

I named it rightClick instead of contextClick

Thanks for the contribution!
