### ISSUE TITLE
"notDisplayed" test should check an element's parents as well

### ISSUE THREAD

**Issue by rmunn** [lefthandedgoat/canopy#274]
I'm testing the signup page of a website. The page uses AngularJS 1.x and, among other things, contains the following HTML: `<span data-ng-show="usernameExists" class="ng-hide"><img id="usernameExists" src="/Site/views/shared/image/exclamation.png" title="User name already exists!" style="position: absolute; padding-left: 5px; padding-top: 8px;"></span>`.

I'm trying to write a test to check if that element is hidden. (I.e., the exclamation-mark icon is NOT visible on the page, because the user has entered a valid username that doesn't already exist on the site). My first attempt was:

    notDisplayed "#usernameExists"

However, this failed -- because the `<img id="usernameExists">` element is never actually hidden! It's its *parent*, the `<span class="ng-hide">` element, that has `display: none`, and Canopy was only checking the visibility of the element, not its document parents. I was eventually able to get the test to work by using a more complicated XPath selector:

    notDisplayed "//*[@id='usernameExists']/parent::span"

However, that's rather ugly. What I'd rather see is Canopy follow the [WebDriver standard rules for checking if an element is displayed](https://w3c.github.io/webdriver/webdriver-spec.html#dfn-element-displayed)... or at least making steps in that direction. The first step, which would have solved my current problem, would have been to recursively climb the document tree up to the root, and check whether any of the element's ancestors are displayed (as per step 10 of that algorithm).

There may be some performance issues here (how expensive is it to climb the document tree like that?), but that can be discussed.

**Comment by lefthandedgoat** [comment]
I had never seen those rules, thats interesting.  Here is the current implementation:

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L532-L535

You can also write that selector like this:

`notDisplayed "[data-ng-show='usernameExists']"`

You can also add a new finder to the pipeline to make it even cleaner:

https://github.com/lefthandedgoat/canopy/blob/master/tests/basictests/Program.fs#L731-L737

`notDisplayed "usernameExists"`

Are these reasonable alternatives?

**Comment by lefthandedgoat** [comment]
Another option may be to change your selector to `notDisplayed "#usernameExists:visible"`

because the more advanced jquery selector engine may do many of the things suggested in the article you linked.

**Comment by rmunn** [comment]
I think I'll go with the "add a new finder to the pipeline" approach, because in addition to looking clean, it will end up demonstrating to my colleagues how F# can lend itself to very clean code. (I'm the first adopter of F# in our company, as far as I know, though some of my colleagues have talked about learning it "sometime".)

That should be enough to solve my problem, so I'll close this issue. Modifying `displayed` and/or `notDisplayed` to match the WebDriver standard rules can come later on -- it could be a breaking change for existing tests, since the rules would change, so some caution might be required. (Though since the current behavior was counter-intuitive to me, I think the change will be worth making.)
