### ISSUE TITLE
The fadedIn function should be documented, maybe in the waitFor docs

### ISSUE THREAD

**Issue by rmunn** [lefthandedgoat/canopy#275]
While looking at #274, I discovered that there's a `fadedIn` function that seems perfect for many situations, such as pages with CSS transitions where an element might need to fully show up before you can test it.

The docs for `waitFor` should include this function in an example, e.g.

    waitFor ("#animatedDiv" |> fadedIn)

I wouldn't have known about this handy function if I hadn't happened to scroll down from the source for `notDisplayed`.

**Comment by lefthandedgoat** [comment]
I will be working on documentation today and I will make sure this is documented

**Comment by lefthandedgoat** [comment]
Thanks for the feedback, this is now documented here: 

http://lefthandedgoat.github.io/canopy/assertions.html
