### ISSUE TITLE
"displayed" and "notDisplayed" ignore the status of the container elements

### ISSUE THREAD

**Issue by svitebskiy** [lefthandedgoat/canopy#277]
Given this HTML fragment:
```
<span id="container" style="display:none">
    <span id="someText">Hello World!</span>
</span>
```

In a Canopy test, the first line of the following 2-line fragment will succeed, but second one will fail, even though the inner span element is also hidden:
```
notDisplayed "#container"    // Passes
notDisplayed "#someText"     // Fails
```

**Comment by lefthandedgoat** [comment]
Yah canopy doesn't walk to the dom to see if parent is not displayed.  2 options, do like you did and check the container, or I think using  the `:visible` jquery psuedo selector to your inner span and it should work.

**Comment by svitebskiy** [comment]
Thank you for the quick response. It just was not completely clear from the docs that displayed/notDisplayed are not supposed check the visibility of the parent/ancestor elements.

**Comment by lefthandedgoat** [comment]
Good feedback. I will update the docks
