### ISSUE TITLE
Css Pattern to find the elements

### ISSUE THREAD

**Issue by danuma** [lefthandedgoat/canopy#278]
Can css Pattern be used to find an element , im having issues with id , xpath , css selector etc to find an element which is not reliable.

**Comment by lefthandedgoat** [comment]
Can you give me an example of a css Pattern?  Googling just returns some nice images created using css.

**Comment by danuma** [comment]
I want to select a td in tr and the id of it keeps changing. 

In Selenium tests Im doing  
  _driver.FindElements(By.CssSelector(cssPattern)) and the cssPattern value as input[id*='Price'] containing regex.

i want to do the similar thing in Canopy.

**Comment by lefthandedgoat** [comment]
`input[id*='Price']`
Is a valid CSS selector and will work with canopy.

```
"input[id*='Price']" << "5.00"
```

Should work

**Comment by danuma** [comment]
Click "input[id*='Price']" -  I tried this and having a hard time . This css selector will return multiple elements , will canopy pick up the first element which matches the pattern.

**Comment by lefthandedgoat** [comment]
If it returns multiple elements then canopy will try to click all of them.

You can use `input[id*='Price']:first` to get the first one and only click it.

**Comment by danuma** [comment]
Cool... will try this.

**Comment by danuma** [comment]
No luck.  when id value is given exactly im able to select the radio button good. As the ID value keeps changing i need to use regex in css pattern.

**Comment by danuma** [comment]
Well , it worked when i did this 

        let radioButton = browser.FindElement(By.XPath("/html/body/divetcetc"))
        click radioButton 

same thing is not working when i said 
       click "#xpath"

Thanks for the help .

**Comment by lefthandedgoat** [comment]
You can try this

http://www.w3schools.com/cssref/sel_attr_end.asp

If its always changing because its a Asp.net Webforms, that will help.

Also you can test out your selectors in Chrome developers tool, open the console on the page and do

`$("div[attribute='whatever'")`
And it will show you how many elements you got, and you can mouse over them.  This will help you write good selectors.

**Comment by danuma** [comment]
Thanks for the reference.

**Comment by danuma** [comment]
I am organizing tests by creating helper functions , which are scattered across multiple .fs files . After every test im closing the browser and opening new one for next test. 

I am defining the elements at the beginning of the module and using them in the functions more than one time in the same module (fs file) , I have trouble with some elements with the exception "Session ID not found". 
eg
//in module
open System
open canopy

//defining the elements
let userid = "#userid"
let password = "#password"

//my helper methods
let login () =
userid << "Name"
password << "abc"

let logincheckerror() =
userid << "name"
password << "xyz"

From Test1 im calling login() , tests runs good and elements are identified. 

From Test2 if logincheckerror() is called the session id for userid and password is lost with an execption Session ID not mentioned.

To overcome the problem, is it possible to initialize these elements every time a method in the particular module is called. 

Thanks

**Comment by lefthandedgoat** [comment]
`To overcome the problem, is it possible to initialize these elements every time a method in the particular module is called.`

I dont understand your question.

Initialize what elements?  userid/password?

What methods? The login/logincheckerror functions?

**Comment by danuma** [comment]
Initialize what elements? userid/password? _ yes 

What methods? The login/logincheckerror functions? - yes  


when I do the following way it is working, but for the easy maintenance and reusability I want to define all the elements in the beginning of the module. 

let logincheckerror() =

let userid = "#userid"
let password = "#password"

 userid << "name"
 password << "xyz"

**Comment by lefthandedgoat** [comment]
the way you have it where you define userid/password above the function works just fine.

They are just strings that are css selectors, and each time you call the function it will try to write the value you into those html elements.

is it not working?

`Session ID not found` sounds like maybe something specific to the application you are testing.

**Comment by danuma** [comment]
It is not working , may be it is my application relation .I have the elements defined within the function as work around for now.
