### ISSUE TITLE
press backspace

### ISSUE THREAD

**Issue by Navmed** [lefthandedgoat/canopy#281]
How can I press backspace? Or other arbitrary keys?

Thanks!
Naveed

**Comment by lefthandedgoat** [comment]
You use the `press` function.

See some examples of keys here: https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L441-L453

and You can make your own, `let backspace = Keys.Backspace`

It just uses the built in selenium enum.  Hope this helps.

**Comment by Navmed** [comment]
That works. Thanks!

It would be useful to add to the documentation. Is the documentation on git? I can't seem to find it. If it is, I can add and submit a pull request.

**Comment by lefthandedgoat** [comment]
Yep you can see it here:
https://github.com/lefthandedgoat/canopy/blob/master/docs/content/actions.fsx

**Comment by rojepp** [comment]
@lefthandedgoat How could I send a key combination, ie `Cmd+S`?

**Comment by lefthandedgoat** [comment]
I think this will work: `press (OpenQA.Selenium.Keys.Command + "S")`
