### ISSUE TITLE
Request: Data driven tests

### ISSUE THREAD

**Issue by katepaulk** [lefthandedgoat/canopy#283]
I'm just getting started with canopy, and I'm loving how simple it is to work with compared to CodedUI, but there's one big thing missing for me: the ability to data drive the tests.

I'd love the ability to run a test with a data set - what I'm doing now (which isn't ideal) is that all the iterations from the data set are one "test".

**Comment by lefthandedgoat** [comment]
One of the things that I try to keep true with canopy is that 'you can do whatever you want'.

You can either iterate your different scenarios in a single test or if you want you can create a test per.

```
type User = { Username : string; Password : string }
let validateLogin user =
  sprintf "Validing login for %s" user.Username &&& fun _ ->
    url "http://yourpage.com"
    "#username" << user.UserName
    "#password" << user.Password
    click "Login"
    on "http://yourpage.com/home"

[
  { Username = "Bob"; Password = "12345678" }
  { Username = "Tom"; Password = "12345678" }
  { Username = "Sue"; Password = "12345678" }
  { Username = "Sally"; Password = "12345678" }
] |> List.iter validateLogin 
```

That should create 4 tests with 'correct' descriptions.

Does this help?

**Comment by katepaulk** [comment]
Yes, it does. It gives me the reporting level I need with the dynamic data I have to work with.

Thank you.

**Comment by lefthandedgoat** [comment]
Awesome!
