### ISSUE TITLE
Is there a way to run the tests based on the context from commandline

### ISSUE THREAD

**Issue by danuma** [lefthandedgoat/canopy#286]
My tests are currently scattered in different contexts as shown in sample project. In case if i want to run only one context at a time , is it possible to execute. 

Do I have to wrap them in NUnit , MsTest frameworks. if so is there any example for it. 

Thanks,

**Comment by lefthandedgoat** [comment]
https://github.com/lefthandedgoat/canopyStarterKit

The starter kit has examples of the code taking arguments, and only run certain tests based on the arguments.
