### ISSUE TITLE
How to Upload File or Images using Canopy?

### ISSUE THREAD

**Issue by kunalthecoder** [lefthandedgoat/canopy#287]
Hi,

I am using Canopy for Automation testing of one of  my web application. at some stage We have functionality to upload images. 

Any idea how can we do it using Canopy?

I have tried following code but no luck.

```
let fileToUpload = FileInfo(Path.Combine(__SOURCE_DIRECTORY__, __SOURCE_FILE__))
"#uploadname1" << fileToUpload.FullName
click "#uploadbutton"
```

**Comment by lefthandedgoat** [comment]
What does not work for it?

Does `"#uploadname1" << fileToUpload.FullName` set the path for the upload control correctly?

**Comment by kunalthecoder** [comment]
Yes, It was not setting up the path correctly. 

Now, It is working fine.
