### ISSUE TITLE
Error message when use: start firefox

### ISSUE THREAD

**Issue by qdai-korewireless** [lefthandedgoat/canopy#288]
Hello,
I got below error when use : start firefox. I installed the latest version of firefox: 48.0.2

> An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll
> 
> Additional information: Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055

**Comment by lefthandedgoat** [comment]
Firefox changed in version 48 and doesn't not work with selenium 2.5x ,
Selenium 3 is not out yet.  You have to use the older version of Firefox
until then.

**Comment by qdai-korewireless** [comment]
ah.. I see. Thanks a lot!
