### ISSUE TITLE
can i count the number of rows in a table?

### ISSUE THREAD

**Issue by MahmoudSamik** [lefthandedgoat/canopy#290]
i want to count the number of tr in a tbody table can i do that ?

**Comment by lefthandedgoat** [comment]
`let count = elements "table tr" |> List.length`

**Comment by MahmoudSamik** [comment]
"table tr" is the name of the table or for example the id of the selected table ?

**Comment by lefthandedgoat** [comment]
"table tr" is a css selector to get the tr's inside of a table.  #id is also css selector to get something by id.  You don't have to use only ids

**Comment by MahmoudSamik** [comment]
i write down this code
let count = elements "table tr" |> List.length
count == "5" 
and i got this msg 
can't check equality on 5 because it is not a string or alert

**Comment by lefthandedgoat** [comment]
When you want to do assertions on non selector values use ===
```
let count = elements "table tr" |> List.length
count == "5" 
```

**Comment by MahmoudSamik** [comment]
thank you 💃

**Comment by lefthandedgoat** [comment]
I am going to close this issue, if you have any more bugs/questions please feel free to open new issues!
