### ISSUE TITLE
Question: How to use runFor?  It is not finding my test or starting browsers

### ISSUE THREAD

**Issue by digitaldrummerj** [lefthandedgoat/canopy#292]
I am trying to test against multiple browsers using runFor but it is not finding any of my tests nor is it starting any browsers.  Is there an example of how to use runFor somewhere that I can look at.  I am trying to test against chrome, firefox, ie and edgeBETA.

**Comment by lefthandedgoat** [comment]
Let me try to cook up an example for you.

**Comment by lefthandedgoat** [comment]
Its broken.  I will fix it tonight and ship a new version tonight.  I will also make a branch on canopyStarterKit that shows how to use it also and link to that.

Thanks!

**Comment by lefthandedgoat** [comment]
You can find the fixed version of canopy here: https://www.nuget.org/packages/canopy/0.9.62

To use it is actually simple, the line before your call `run()` add this `runFor [chrome; firefox]`

Then it will duplicate your tests, once for chrome and once for firefox.

Right now firefox is in a weird state, and you need to use a version < 48 for it to work with the current version of selenium.  I would suggest you use the Extended Support Release version that you can download here: https://www.mozilla.org/en-US/firefox/organizations/
