### ISSUE TITLE
Can we check for the Javascript errors on the website ?

### ISSUE THREAD

**Issue by danuma** [lefthandedgoat/canopy#294]
Is there any feature of canopy that will check for the java script errors on the web application. Also , can we do accessibility testing ?

**Comment by lefthandedgoat** [comment]
I am not sure how to even do accessibility testing manually, so I am not sure what the automated version of that would be.

For catching all javascript console errors,  I don't think selenium for .net has a built in option.  I think your best option is maybe some custom javascript that catches all the errors and puts them in a `div`, or `ul` and you check that with selenium.

Sorry =(

**Comment by amirrajan** [comment]
You can run add an additional parameter to Chrome's startup:

```
let openBrowser _ =
  configuration.chromeDir <- "./"
  let options = Chrome.ChromeOptions()
  options.AddArgument("--enable-logging")
  options.AddArgument("--v=0")
  start (ChromeWithOptions options)
  clearCookies ()
```

The Chrome debug logs will be saved to the `CHROME_LOG_FILE` environment variable. Here is what mine is set to (this will save it to where ever the tests are being executed from:
`export CHROME_LOG_FILE="chrome_debug.log"`

You can then tail the file to see if there are any JS errors.

**Comment by lefthandedgoat** [comment]
I am going to close this issue, if you have any more bugs/questions please feel free to open new issues!
