### ISSUE TITLE
Click action behaviour

### ISSUE THREAD

**Issue by milkeg** [lefthandedgoat/canopy#295]
Hello,
I am using Click action to close notifications, but it seems that the Click action remains "activated" and closes also following notifications (which happen less than a second after).
I would like to know the behaviour of the Click action :
- Click action only triggers one click ?
- Click action will click until a timeout is reached and might click more than once ?
- Is the click action asynchronous and remain "activated" even is following commands are executed ?

HTML

```
<div class="alert-success">
    <button type="button" class="close" ng-click="notification.closeMessage();">
        <span aria-hidden="true">×</span>
    </button>
    <span>Your order has been sent.</span>
</div>
```

F#

```
let closeSuccessfMsg = "div[class~='alert-success'] > button[class~='close']"
click (element closeSuccessfMsg)
```

Thank you,

**Comment by lefthandedgoat** [comment]
I dont know all of your html but a few small things
You dont have to get the element then click it, click takes selectors also.

```click ".close"``` would probably do the same thing for you as what you have above and be simpler.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L656-L665

Click with a selector will get all the elements that you have that meet the criteria of your selector, and click all of them.  You are using it with a single element that you have already retrieved, so I don't see how that could do what you are saying happened, where it clicks more than one item.

Click with a selector will try to click things until it clicks something that matches the selector w/o an exception being thrown (like its obstructed by something, or the element is stale).

Click with an element is naive and simply calls .Click() on it.

```
Is the click action asynchronous and remain "activated" even is following commands are executed ?
```

I don't totally understand your question but I think the answer is no.

What is the html of the 2nd popup?

**Comment by milkeg** [comment]
Thanks for the clarifications.

As my 2 notifications are totally similar, I am thinking that the closing click of 
the first notification might also close the second one. This is why I asked if the Click action was remaining "Active" and could Click on more than one element. This situation happens one time out of 20, but in WIP mode it doesn't happen at all (may be because execution is slower).

```
Action 1: Click on a button that triggers a Notification --> OK
Action 2: Check if Notification is displayed --> OK
Action 3: Close the Notification by clicking "x" --> OK
Action 4: Click on a button that triggers the same notification --> OK
Action 5: Check if Notification is displayed  --> KO, but I can see that the notification popped-out
and then got closed right away. 
Action 6: Close the Notification by clicking "x"
```

Is there a way to implement WebDriverEventListener under Canopy ?

**Comment by lefthandedgoat** [comment]
I think you can after reading this:

https://seleniumeasy.com/selenium-tutorials/webdriver-event-listener-example

You will need to create a new class that implements that the interface.

Start a browser, Pass that browser to your new instance of evenlistening browser, then `browser <-yourEventListeningBrowser` (maybe with a cast).

I have never done this.  If you get stuck let me know and I can try to figure it out.

**Comment by lefthandedgoat** [comment]
I am going to close this issue, if you have any more bugs/questions please feel free to open new issues!
