### ISSUE TITLE
page objects and sections

### ISSUE THREAD

**Issue by quezlatch** [lefthandedgoat/canopy#296]
so i know it's pretty straightforward to do page objects using modules, but what about sections in the way the [Site Prism](https://github.com/natritmeyer/site_prism#sections) might do it.

This would be useful, for example, where I have multiple components of the same type on one page, and want to be able to interact with them independently.

Thanks,

**Comment by lefthandedgoat** [comment]
It looks like they are just creating classes with properties, then have 'parent' pages have a property of the 'sub' class in it.

You can do this with records pretty easily, since generally your page definition is a bunch of selectors represented as strings.


```
type Header = 
  {
     Home : string
     Login : string
     Logout : string
  }

let defaultHeader = 
  {
    Home = "#home"
    Login = "some other selector"
    Logout = "some other selector"
  }
```

Then on your page object via modules 

```
module UserPage

let header = defaultHeader
```

Or, if you want defaultHeader with some small changes

```
module UserPage

let header = { defaultHeader with Home = "a different selector" }
```

I think this will provide what you are asking for?

**Comment by quezlatch** [comment]
sort of... the special source is the section element are within the bounding section element. i.e.:

```
<div>
    <div id="a">
        <input name="xyz" value="1" />
    </div>
    <div id="b">
        <input name="xyz" value="2" />
    </div>
</div>
```

```
module fields
let input = "input[name=xyz]"
```

not working approximation of f# code...
```
module page
let a = section fields "#a"
let b = section fields "#b"
```

the assertions
```
page.a == "1"
page.b == "2"
```

**Comment by lefthandedgoat** [comment]
You can make a function that does this for you.  This one will only work on CSS selectors, but if thats all you use then you are good!


```
let section prefix selector = sprintf "%s %s" prefix selector

module Common
let header = "#header"

module UserPage
open Common

let editPreferences = section header "a[href='/edit']"

module UserPageTests
open UserPage 
click editPreferences
```

I think this gives you something similar

**Comment by quezlatch** [comment]
not sure. i think that might the inverse of what i was getting at, but that may be my oo instead of fp thinking.
so i think **Common** should have the editPreferences `a[href='/edit']` and **UserPage** should have the header `#header`. That way **UserPage** could also have a  `#header1`,  `#header2` and  `#header3`.
We would then be able use editPreferences from header, header1, etc.

**Comment by lefthandedgoat** [comment]
Yah you can organize it how you like.  I guess the main point is that, if you have a 'root' css selector, you have have 'children' ones in there, by just concating them together with a space between

`.root .children`

or in xpath

`\root\path\\children\path`

And you can make yourself some little helper functions to manage that for you.

**Comment by quezlatch** [comment]
that makes sense. i'll a have a little play with some helpers and see how i get on. many thanks

**Comment by lefthandedgoat** [comment]
I am going to close this issue, if you have any more bugs/questions please feel free to open new issues!
