### ISSUE TITLE
using firefox in canopy

### ISSUE THREAD

**Issue by singh83** [lefthandedgoat/canopy#299]
i have installed Firefox webdriver but still firefox not working, like chromeDir , is there any special name for FireFox in canopy.configuration

**Comment by lefthandedgoat** [comment]
Read this: https://github.com/lefthandedgoat/canopy

This will change soon once I get selenium 3.0 brought in and tested out.

**Comment by singh83** [comment]
installed latest canopy and selenium and Firefox version 45 then downloaded sample application for testing canopy and then firefox open correctly 
For my project if i used start chrome then chrome open fine but when i use start firefox i got below error
OpenQA.Selenium.WebDriverException was unhandled
Message: An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll
Additional information: Unable to determine the current version of FireFox using the registry, please make sure you have installed FireFox correctly

**Comment by lefthandedgoat** [comment]
this sample application? https://github.com/lefthandedgoat/canopyStarterKit

**Comment by singh83** [comment]
not that one but this one https://github.com/oinant/CanopyTryout.git

**Comment by lefthandedgoat** [comment]
I get the same error now.  It looks like the ESR version uses different registry keys and its causing selenium to fail.

Selenium 3 is out now and it switches to a driver based model like chrome and IE.  I will being working on getting canopy updated to it.  I hope that it takes just a few days.

Sorry for the problems.

**Comment by singh83** [comment]
Chris,
Thanks for your quick response.
But how firefox working fine for sample application i have downloaded ?

Thanks

**Comment by lefthandedgoat** [comment]
You want to know how to get it to work for the sample app?

**Comment by singh83** [comment]
For sample app it is working fine already , they are using same selenium and canopy version,
And in my project i am using same way but its not working for my project.
Is there any work around we can use before you release latest canopy version.

Thanks

**Comment by lefthandedgoat** [comment]
This worked for me:

```
start (FirefoxWithPath @"C:\Program Files (x86)\Mozilla Firefox\firefox.exe")
```

Not that you may have to remove the `(x86)` part

**Comment by lefthandedgoat** [comment]
Can you tell me what error message you are getting in your project?

**Comment by singh83** [comment]
i already send you error message and you replied that you are also getting same errro, but i got your work around option and i will try that and will update you if have any issue,
I never got such prompt reply from any other blog. I appreciate your feedback.

**Comment by lefthandedgoat** [comment]
You are welcome.  I am at home sick so it is easy =)

With Firefox ESR and the sample app your linked to, I was getting the same error as you.  Using `start (FirefixWithPath "c:\....")` that I showed above did make it work for me though, and I think it will for you.

**Comment by singh83** [comment]
Hope you get well soon.

**Comment by lefthandedgoat** [comment]
updating to selenium 3 was easier than I thought.  You can read the instructions on what you have to do in issue 300 here : https://github.com/lefthandedgoat/canopy/issues/300

**Comment by singh83** [comment]
everything work fine if i copy geckodriver.exe into bin\debug folder, otherwise it through following exception, Where should i copy that file so that when i compile project it automatically moved to bin\debug folder just like CanopyStarterKit
OpenQA.Selenium.DriverServiceNotFoundException was unhandled
Message: An unhandled exception of type 'OpenQA.Selenium.DriverServiceNotFoundException' occurred in WebDriver.dll
Additional information: The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.

**Comment by lefthandedgoat** [comment]
This commit shows how to do it.  You need to drop it in a folder, then add it to the project and set it to copy on build.

https://github.com/lefthandedgoat/canopyStarterKit/commit/9705843bff78b48676d6d44fc67585e1600c687d

**Comment by singh83** [comment]
All done well. thanks for all your help. I am closing this issue
