### ISSUE TITLE
can we assert text in pdf file downloaded after clicking link on page

### ISSUE THREAD

**Issue by singh83** [lefthandedgoat/canopy#306]

**Comment by lefthandedgoat** [comment]
Selenium can not interact with pdf files.  You will need to find a library that can and use it in your tests after you download the file.

**Comment by singh83** [comment]
thanks, i will try to find any such library and will update here as well so that in future if anybody need can use that library.

**Comment by lefthandedgoat** [comment]
Sounds good!
