### ISSUE TITLE
Selecting a .NET Framework 

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#309]
I'm setting up canopy in a new environment, running VS 2015 Enterprise. VS prompted me to install Visual F# so I did. I didn't recall installing it last spring on my other machine. 

Following the startup instructions  on the Canopy website, I noticed when creating a project, I'm instructed to select .NET Framework 4. VS, however, supports up to v4.6n.

Do you support the higher versions? Will I get myself in trouble using them? Should I just stick with v4.0?

**Comment by katepaulk** [comment]
For myself, I've had no issues with a high version of the .NET framerwork, but you will probably have to add a few binding redirects to your app.config file

I've had to add the following:
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="4.3.0.0-4.3.1.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding> 
  </runtime>

**Comment by lefthandedgoat** [comment]
Yes any version should work, and if you want to use a newer version the binding redirects that katepaulk provided should work.  If it does not work please let me know and I will create a working sample for you and put it on github.

**Comment by sprice9161** [comment]
Thank you both!

**Comment by sprice9161** [comment]
Once you create a folder and file, exit out of VS and reopen VS, is the time still there. My first one was. IF I add a second folder/file pair at the same level or nested it fails. The project will not open in the solution explorer, and you have to remove the new entry from the ".proj" file.

**Comment by sprice9161** [comment]
Hi Chris, you can close this ticket if you like but I would like to know if there is an order of file precedence in a canopy/ F# project and what that entails.

**Comment by lefthandedgoat** [comment]
The ticket is already closed.

I F# file order does matter.  You can only use code from a file that is defined above the one you are working in.  Top down.

https://fsharpforfunandprofit.com/posts/cyclic-dependencies/

**Comment by amirrajan** [comment]
@sprice9161 I'd strongly recommend you taking the time to read all the content on https://fsharpforfunandprofit.com/. There is a ton of good stuff there. 

Asking about order of file precedence is a general F# question and isn't really related to Canopy.

**Comment by sprice9161** [comment]
Way to promote the tool Amor...
