### ISSUE TITLE
How can I get the name of the test into a screenshot filename without copy + paste?

### ISSUE THREAD

**Issue by lotsahelp** [lefthandedgoat/canopy#311]
In Selenium C# I am able to use CallerMemberName to save screenshots with the test name in the filename. This is more meaningful than just a timestamp. How could I do something similar with Canopy? 

Thank you,

**Comment by lefthandedgoat** [comment]
This code here does it:

https://github.com/lefthandedgoat/canopy/blob/master/tests/basictests/Program.fs#L18-L23

You can tweak it to be however you like.

**Comment by lotsahelp** [comment]
Thanks. That worked great.
