### ISSUE TITLE
correct build procedure

### ISSUE THREAD

**Issue by Biarity** [lefthandedgoat/canopy#312]
I'm trying to build the project, using the FAKE target `all`, but I keep getting errors (build fails), are there extra steps to building? (I want to obtain the dll)

**Comment by lefthandedgoat** [comment]
You can download the dll by downloading the nuget package here and unzipping it:

https://www.nuget.org/packages/canopy/

Yes you can also build by cloning source and running `build.cmd` on windows or `sh build.sh` on *nix.

If you are getting errors you need to paste them here so I can help you with them.

**Comment by Biarity** [comment]
Yes, I am following that build procedure but I get this error when building on Windows 10:
```
Build FAILED.

       "c:\...\canopy-master\canopy.sln" (Rebuild target) (1) ->
       "c:\...\canopy-master\tests\basictests\basictests.fsproj" (Rebuild target) (2) ->
         c:\...\canopy-master\tests\basictests\basictests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.


       "c:\...\canopy-master\canopy.sln" (Rebuild target) (1) ->
       "c:\...\canopy-master\src\canopy\canopy.fsproj" (Rebuild target) (3) ->
         C:\...\canopy-master\src\canopy\canopy.fsproj : error MSB4057: The target "Rebuild" does not exist in the project. [c:\...\canopy-master\src\canopy\canopy.fsproj]


       "c:\...\canopy-master\canopy.sln" (Rebuild target) (1) ->
       "c:\...\canopy-master\src\sampleprojectstructure\sampleprojectstructure.fsproj" (Rebuild target) (4) ->
         C:\...\canopy-master\src\sampleprojectstructure\sampleprojectstructure.fsproj : error MSB4057: The target "Rebuild" does not exist in the project. [c:\...\canopy-master\src\sampleprojectstructure\sampleprojectstructure.fsproj]

    0 Warning(s)
    3 Error(s)

Time Elapsed 00:00:00.59
Running build failed.
```
I am aware I can use NuGet but just curious about the source of these errors. Thanks for the help!

**Comment by lefthandedgoat** [comment]
One of the people that uses canopy still uses VS 2010 due to constraints at work, so I build it with F# 3.0.

To build from command line you need to install this.

https://www.microsoft.com/en-us/download/confirmation.aspx?id=34675

Sorry for any inconvenience!

**Comment by Biarity** [comment]
No worries, I extracted it from nupkg.
