### ISSUE TITLE
LiveHtmlReporter() no longer compatible with Selenium Webdrivers

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#313]
I haven't run my scripts since the late spring, but everything was working. I went to my project and updated canopy to the latest build.

I couldn't update Selenium Webdrivers to 3.01, so I updated to 3.0, which I saw on this site you are now supporting. 

Running the script fails on the HTML reporter that I implemented when I first created the script. This is the reporter that you describe using on "Frictionless Web Testing".

My concern is that the reporter is no longer working due to the updates.

Code:
open reporters
reporter <- new LiveHtmlReporter() :> IReporter

Warning: 
DriverServiceNotFoundException was unhandled

An unhandled exception of type 'OpenQA.Selenium.DriverServiceNotFoundException' occurred in WebDriver.dll

Additional information: The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.

**Comment by lefthandedgoat** [comment]
This part of the error message tells you what you need to do.

```
Additional information: The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/geckodriver/releases.
```

This issue tells you were to place gecko driver:

https://github.com/lefthandedgoat/canopy/issues/300

**Comment by sprice9161** [comment]
I just saw one of your earlier issues....Thank you.

**Comment by lefthandedgoat** [comment]
I am going to close this issue, if you have any further issues please feel free to open a new one!
