### ISSUE TITLE
Adding a new FireFox browser cosntructor

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#315]
Please add a new FireFox constructor with option and timespan as:

`| FirefoxWithProfileAndTimeSpan of Firefox.FirefoxProfile * TimeSpan`

This will allow customizing startup option; such as disabling cache, etc.

**Comment by amirrajan** [comment]
Can you give a bit more detail on what you're trying to accomplish?

`Program.fs` is just a console app. So you could add a `Console.ReadLine()` that doesn't start the tests until you're ready to.

**Comment by galatrash-at-dnn** [comment]
The file `type.fs` contains these:
```
//browser
type BrowserStartMode =
    | Firefox
    | FirefoxWithProfile of Firefox.FirefoxProfile
    | FirefoxWithPath of string
    | FirefoxWithUserAgent of string
    | FirefoxWithPathAndTimeSpan of string * TimeSpan
    | IE
    | IEWithOptions of IE.InternetExplorerOptions
    | IEWithOptionsAndTimeSpan of IE.InternetExplorerOptions * TimeSpan
    | EdgeBETA
...
```
and `canopy.fs` contains
```
    browser <-
        match b with
        | IE -> new IE.InternetExplorerDriver(ieDir) :> IWebDriver
        | IEWithOptions options -> new IE.InternetExplorerDriver(ieDir, options) :> IWebDriver
        | IEWithOptionsAndTimeSpan(options, timeSpan) -> new IE.InternetExplorerDriver(ieDir, options, timeSpan) :> IWebDriver
...
        | Firefox -> new FirefoxDriver() :> IWebDriver
        | FirefoxWithProfile profile -> new FirefoxDriver(profile) :> IWebDriver
        | FirefoxWithPath path -> new FirefoxDriver(new Firefox.FirefoxBinary(path), Firefox.FirefoxProfile()) :> IWebDriver
        | FirefoxWithUserAgent userAgent -> firefoxWithUserAgent userAgent
        | FirefoxWithPathAndTimeSpan(path, timespan) -> new FirefoxDriver(new Firefox.FirefoxBinary(path), Firefox.FirefoxProfile(), timespan) :> IWebDriver
        | Safari ->new Safari.SafariDriver() :> IWebDriver
...
```

What I'm asking is another option for starting firefox while specifying some options and timeout. The options will allow me to control the FireFox driver  (e.g., disable caching).

**Comment by lefthandedgoat** [comment]
sure I can add it. Today I am traveling so it may be tomorrow before I create a new build

**Comment by lefthandedgoat** [comment]
You can download this change here:

https://www.nuget.org/packages/canopy/1.0.5

Thanks for the ticket!

**Comment by galatrash-at-dnn** [comment]
That's great. Thank you.
