### ISSUE TITLE
Access to driver.PageSource?

### ISSUE THREAD

**Issue by lotsahelp** [lefthandedgoat/canopy#316]
I'm trying to test against a raw xml response that one of our pages return but cannot figure out how to access the current driver.PageSource to be able to pass that to an XmlProvider. What would be the best way to get access?

Thank you,

**Comment by lefthandedgoat** [comment]
`browser` in canopy is the selenium driver.  If you are going to a page that is returning the XML, chrome will give you a nice html representation of it, but its very hard to test.  It may be best to do an http request against the url to get the xml, then give it to the xml provider.  I like https://github.com/haf/Http.fs for that purpose.
