### ISSUE TITLE
waitFor(fun _ -> currentUrl() = 'foo') is slow after form submission

### ISSUE THREAD

**Issue by knocte** [lefthandedgoat/canopy#319]
I've got a problem with a test that is really slow and was hoping for some advice from the canopy community :)

The scenario is the following: there's a form in url http://example.com/ that has a submit button. When I use `click submit` with canopy, the result of this is that the form is submitted, and then the browser gets redirected to a new URL http://example.com/loggedIn.

So then, I have this:

```fsharp
click submit
waitFor(fun _ -> currentUrl().EndsWith("/loggedIn"))
```

The page http://example.com/loggedIn loads a bit slowly because it contains images and my bandwidth is not very high. However, I can see very clearly, that the address bar of the URL changes to http://example.com/loggedIn very fast. However, the call to `waitFor()` gets blocked until the whole page is loaded (hence waiting to retreive all the images).

Is there a faster way to get an event from the moment the address bar of the browser changes?
Thanks

**Comment by lefthandedgoat** [comment]
Once a page transitions selenium blocks until the page is loaded completely
so the behavior you are seeing is normal. Also you can use the `on`
assertion to check the URL too.  I don't know if there is a setting to
change selenium behavior.
