### ISSUE TITLE
Removing the "tcFriendlyMessage image" from TeamCity log

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#324]
If the image capturing is enabled and there are many images captured, then dumping the content of these into the text stream of the reporter is making the generated report huge.

Is there a way to disable this image dump (the code: ``tcFriendlyMessage image``) in the TeamCity reporter?

**Comment by lefthandedgoat** [comment]
I followed the code and I am 90% sure that if you set this to false, screenshots wont be taken, and wont be put in your messages.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/configuration.fs#L71

Images in tc messages exist btw because using some tricks you can have failure images embedded into your team city report.  I have a gist on how to do it if you are interested.

**Comment by galatrash-at-dnn** [comment]
Maybe you misunderstood me. I need the screenshots to stay, but don't want the image being dumped as a string to appear in the log. Here is a sample of what I get in my TeamCity logs which is making the logs very huge:
```
  FAIL: 
	UI element "#Manage > #GlobalAssets" is visible.
[23:11:38]canopy-image(iVBORw0KGgoAA ... a huge KB of text here ... ORK5CYII=)
```

**Comment by lefthandedgoat** [comment]
You want the images written to a file and saved as a png but not in the console?

I would have to add a flag for that to disable TC images.

The only way to that I know of to get inline images in TC is to write them to the console like that.

**Comment by galatrash-at-dnn** [comment]
A flag would be great. I'm not interested in inlined images in TC report.

**Comment by lefthandedgoat** [comment]
ok cool I can do that for ya

**Comment by galatrash-at-dnn** [comment]
Thanks a lot.

**Comment by lefthandedgoat** [comment]
You can find a new package here: https://www.nuget.org/packages/canopy/1.0.7

```
reporter <- new TeamCityReporter(false) :> IReporter
```
