### ISSUE TITLE
Add a way to save document

### ISSUE THREAD

**Issue by rojepp** [lefthandedgoat/canopy#326]
My use case: I'm scraping the Azure portal in order to download my monthly invoice as a pdf. When my script gets to the download link, it would be nice to be able to right-click/save as or click the link and when the PDF page shows up (Chrome), save the current document from the script, with its suggested filename in a given path.

**Comment by lefthandedgoat** [comment]
This worked for me.

Let me know if this does not work for you.  You just need to start chrome differently to disable the PDF viewer and auto download files and then you can just click the link and it will save to the directory you set.

open canopy
open runner

let options = OpenQA.Selenium.Chrome.ChromeOptions()
//Set to your pref dir
options.AddUserProfilePreference("download.default_directory", @"C:\Users\TEMP")
options.AddUserProfilePreference("profile.default_content_settings.popups", 0)
options.AddUserProfilePreference("download.prompt_for_download", false)
options.AddUserProfilePreference("plugins.plugins_disabled", [| "Chrome PDF Viewer" |] )

start (ChromeWithOptions options)

url "http://www.pdfpdf.com/samples.html"

click "a[href='samples/Sample1.PDF']"

**Comment by rojepp** [comment]
Worked like a charm! Thanks for being so helpful!

**Comment by lefthandedgoat** [comment]
Great! No problem!

**Comment by rojepp** [comment]
@lefthandedgoat Sorry to bother you again, but this approach seems to not work since Chrome 57.
This is what I've been able to find: https://productforums.google.com/forum/#!topic/chrome/ZQJFOB3o3EQ 
Any ideas?

**Comment by lefthandedgoat** [comment]
Remove this 4th option 
`options.AddUserProfilePreference("plugins.plugins_disabled", [| "Chrome PDF Viewer" |] )`

and replace with

` options.AddUserProfilePreference("plugins.always_open_pdf_externally", true)`

Found here: http://stackoverflow.com/a/42927095/697586
