### ISSUE TITLE
Css selector suggestor

### ISSUE THREAD

**Issue by Jmcclintick** [lefthandedgoat/canopy#330]
Would be so cool if you had a browser plug in that would allow point and click tests to gain more adoption from the business users. In general I still think tests belong as close to the code as possible but I could see this as a starting point for the business to help get a jump start on coverage. My thought is that I click through a test case and the output is a canopy test that can then be analyzed and refined to insure the intent of the business was accurately captured. Over time you will gain efficiencies and be able to better capture intent.

**Comment by lefthandedgoat** [comment]
Just for you.

**Comment by lefthandedgoat** [comment]
I will start with a css selector thing, then generating tests may follow.

**Comment by lefthandedgoat** [comment]
@Jmcclintick Justin I am make great progress.  When are you available for some UAT?

**Comment by lefthandedgoat** [comment]
Boom done!

https://chrome.google.com/webstore/detail/canopy-companion-css-sele/jehfnloleecojodohcdfpbhjahhaplje

Still room for improvements but its very usable now and useful.

**Comment by Jmcclintick** [comment]
I'm always available for some UAT! 

Works really well! This could definitely help gather some of those pesky selectors!
