### ISSUE TITLE
Reusing Tests and REPL

### ISSUE THREAD

**Issue by navmed** [lefthandedgoat/canopy#331]
In my web-app that I'm testing, I have a number of fields that have the same behavior, so I have this reusable code:
```
let testCrudAdd fieldName selector newValue = 
    fieldName + " CRUD Add" &&& fun _ ->      // Uncomment when running tests, it doesn't run on the REPL
        click selector
        (selector + " .custom-dropdown__input--active") << newValue
        press enter
        (selector + " .custom-dropdown__span") == newValue
```

and I call it:

`testCrudAdd "Referral Source" "#referral-source" "jokdjoiajsoein"`

This works fine when I run the code regularly, but on REPL I have to remove the 2nd line with test declaration. IIRC this used to work on an older version of canopy. 

Is there a better way to do reusable tests?

**Comment by lefthandedgoat** [comment]
You have to import the dlls into the REPL for it to work

```
#I @"C:\projects\fsxCanopy\packages\Selenium.WebDriver.3.0.0\lib\net40\"
#I @"C:\projects\fsxCanopy\packages\canopy.1.0.6\lib"

#r "WebDriver.dll"
#r "canopy.dll"

open canopy
open runner

```
Adjusts paths to your setup

**Comment by navmed** [comment]
I do have them, under REPL it doesn't throw an error. It just shows

`val it : unit = ()`

To actually make it run the test, I have to comment the 2nd line.

**Comment by lefthandedgoat** [comment]
```run ()```

run that in REPL after you register your test

**Comment by navmed** [comment]
That worked. Thanks!
