### ISSUE TITLE
Adding directories to a canopy f# project 

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#332]
I tend to structure my "test_xxx.fs" files based on the requirements tree. This current project the Business Analysts created a requirements tree 3 and 4 levels deep with extremely long names, so you can imagine the length of my file names.

What I would like to do is add folders representing test suites in the project tree, but the files will physically be in different folders, not just mapped. 

Can this be done under the current canopy/f# structure, and how?

**Comment by lefthandedgoat** [comment]
Right click on your project in Visual Studio Solution Explorer, add a folder, move the files to the folder.

**Comment by sprice9161** [comment]
I worked with one of our C# developers on this. There is no option to add a folder. We googled it and found 2 solutions. One requires you to download and install VisualF# Power tools (haven't tried that yet), The other was to unload the project and edit the xxx.fproj file adding an entry to the <ItemGroup><Compile Include="directory path\\filename.fs">. I'm assuming that these are relative paths to the top project layer. This would also move test files into a directory removed from my Programs.fs, and I'm not certain that they will execute or even compile. 

Going back to your suggestion, is there a way to enable "Add Folder" to my project? The developer told me that the files are actually at the same level but appear to be organized into the different folders so that the project should still execute as before.

**Comment by lefthandedgoat** [comment]
The power tools and manually editing the fsproj file both work. You may
find power tools easiest

**Comment by sprice9161** [comment]
Thanks...I'll give it a try.

**Comment by sprice9161** [comment]
Just my 2 cents....
I think it would be helpful for beginners to know about adding power tools on the Canopy site. Also, there is a minimum ".NET" framework required to be able to install it. I was running 4.0 and it failed, so I recompiled under 4.5.

**Comment by lefthandedgoat** [comment]
Ok

**Comment by sprice9161** [comment]
Never mind....
There are a couple of other steps to enable the feature .
Tools->Options 
Select F# Power tools
Select File Management (Off by default)
Restart Visual Studio

**Comment by sprice9161** [comment]
The directories I create using the F# powertools disappear when I restart VS and open the project. I've been performing a "save all" as I create the structure. I've done this twice now. IS there a trick that I don't know about?

**Comment by lefthandedgoat** [comment]
I just installe the power tools, added a folder called test via the power tools menu.  Then added a .fs file called tests by right clicking the new folder.  Saved all.  Close visual studio.  Open again, it is still there.  The proj file was modified correctly.

What version of VS are you using?

The other option is to open your .fsproj file in notepad++ or something similar and add a new line for your new file that is nested in a folder.  This is what I do personally I use a text editor with no GUI.  You need to add new the folder and file in Windows explorer first, then edit the fsproj.  Once you have the folder there once, with a new file it, then you can add files like normal in VS.

**Comment by lefthandedgoat** [comment]
@sprice9161 I also improved support for using canopy for C#.  It may be worth evaluating that if you are more comfortable there.

https://github.com/lefthandedgoat/canopy/blob/master/csharptests/Program.cs
