### ISSUE TITLE
Comparing 2 empty strings produces CanopyReadException

### ISSUE THREAD

**Issue by koenmetsu** [lefthandedgoat/canopy#334]
**Test case**
`(nth 2 "td.data-table__body-title").Text == row.To // both sides evaluate to an empty string`

**Actual behavior**
Throws CanopyReadException

**Expected behavior**
Does not throw exception, just passes and continues.

**Comment by lefthandedgoat** [comment]
You want to use ```===``` for unit test style equality checking.

```==``` takes a selector on the left and a value on the right, and will find the element and try over and over until the values are equal.

**Comment by koenmetsu** [comment]
Yep, seen it now. Would it be an idea to provide a useful warning in case
of empty strings?

On Jan 19, 2017 17:54, "Chris Holt" <notifications@github.com> wrote:

You want to use === for unit test style equality checking.

== takes a selector on the left and a value on the right, and will find the
element and try over and over until the values are equal.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/lefthandedgoat/canopy/issues/334#issuecomment-273832030>,
or mute the thread

**Comment by lefthandedgoat** [comment]
Using this example
```
start chrome
url "http://www.pdfpdf.com/samples.html"
(nth 2 "div").Text == ""
```

I get this error

```
Couldn't find any elements with selector '', did you mean:
	日本語
	Sales
	FAQ's
	PDF4U
	Links
canopy.types+CanopyEqualityFailedException: can't find element 
```

2nd div on that page has an empty Text property which you can see with the `selector ''` part in the error.

The only way that I can reproduce a CanopyReadException is this

`null == ""`

`==` can actually take a string or an alert, thus its not `string == string` its `'T == string` and null can be a null object or null string.  I throw a read exception if its not a string or not a IAlert and null is neither in this case I guess.

Does this help clear it up?  Just an odd scenario for some reason.

**Comment by koenmetsu** [comment]
I must've misdiagnosed something cause I get that read exception. Thanks
for the clarification, I've now moved to === but if I get a chance I'll
investigate further. Mainly wanted to prevent weird errors from preventing
canopy adoption :)

**Comment by lefthandedgoat** [comment]
Thanks I understand.  Maybe I can improve it.  Can you post the full error and stack trace?

**Comment by koenmetsu** [comment]
Error:
```was unable to read item for unkown reason```
Stack:
```
   at canopy.wait.innerwait@10[b](Stopwatch sw, Double timeout, FSharpFunc`2 f) in C:\projects\canopy\src\canopy\wait.fs:line 25
   at canopy.wait.waitResults[a](Double timeout, FSharpFunc`2 f) in C:\projects\canopy\src\canopy\wait.fs:line 10
   at canopy.core.op_EqualsEquals[a](a item, String value) in C:\projects\canopy\src\canopy\canopy.fs:line 511
   at SomeProject.UiTests.SomeBuildingsTab.compareRow(SomeBuildingRow row) in C:\code\SomeProject\test\SomeProject.UiTests\SomesPage.fs:line 64
   at SomeProject.UiTests.CreateSomePageTests.all@58-2.Invoke(Unit _arg4) in C:\code\SomeProject\test\SomeProject.UiTests\CreateSomePageTests.fs:line 108
   at canopy.runner.tryTest[a,b](a test, b suite, FSharpFunc`2 func) in C:\projects\canopy\src\canopy\runner.fs:line 134
```

![image](https://cloud.githubusercontent.com/assets/1169539/22140599/a6bc0bc8-deed-11e6-9da8-0aac2be261c8.png)

**Comment by lefthandedgoat** [comment]
Ok thanks.  I should be able to repro this correctly now.

**Comment by lefthandedgoat** [comment]
I couldn't repro with `"" == ""`

If the page you are testing public?  Maybe I can recreate the issue that way.

**Comment by koenmetsu** [comment]
Yes it's public. I'll see what I can do.

**Comment by amirrajan** [comment]
Is this still an issue @koenmetsu?

**Comment by koenmetsu** [comment]
No, closing it would be fine for me.
