### ISSUE TITLE
Remove selection / focus from link or click on browser window

### ISSUE THREAD

**Issue by uzhas-sovka** [lefthandedgoat/canopy#336]
Imagine that at the end of F# Canopy script I have a page with one selected link. "Selected" means this dotted rectangle around link (as when you keep pushing TAB button manually).

How can I remove this selection? 

In "manual mode" I just click somewhere on browser window, but it seems there is no such function in Canopy like

click Xpos Ypos

The problem is not in removing selection itself. When the link is "selected", the other staff on page doesn't work, I can't do anything like

click "#element"

because "element is not visible". Right now I keep on refreshing page and selection goes away, but it's clumsy and slow.

**Comment by lefthandedgoat** [comment]
you can try `click "html"`

If that does not work, try to find a public page that you can recreate it on and I will run the script and figure something out.

**Comment by uzhas-sovka** [comment]
Thanks for prompt answer. Selection goes away, but element is still missing. So, the problem is not in selection.
