### ISSUE TITLE
Is there an assertion to check Http status code?

### ISSUE THREAD

**Issue by marisks** [lefthandedgoat/canopy#337]
This is useful to assert that correct status codes are returned for 404 and 500 pages.

**Comment by lefthandedgoat** [comment]
I did some googling and it does not seem possible to get status codes from Selenium.

For what you want it may be best to send an HTTP request.  I use this library for F# http stuff:  https://github.com/haf/Http.fs

**Comment by marisks** [comment]
Thanks, it will help!
