### ISSUE TITLE
Fullpage Screenshot Enhancement

### ISSUE THREAD

**Issue by whiteleyj** [lefthandedgoat/canopy#338]
I'm struggling to get full page screenshots working again after firefox finally started taking only screenshots of the visible area.  Realistically I've disabled updates on firefox and am not updating canopy until I can get this working properly.  I'm hoping someone else has had this issue and knows of a reliable way to get the old functionality back.  I think it would be a pretty nice to have enhancement if it could be done.

**Comment by lefthandedgoat** [comment]
Full page meaning the entire length of the page even if it requires scrolling down?

**Comment by lefthandedgoat** [comment]
Hmm some googling shows that the Selenium w3 spec says to only take a screenshot of the viewport.

https://github.com/seleniumhq/selenium/issues/1141

I have no clue how to implement this, I simply wrap the selenium call and if it fails, fall back to windows take a screenshot of the entire desktop + open apps.

**Comment by msttesting** [comment]
@whiteleyj @lefthandedgoat Any update found? Share with us..

**Comment by whiteleyj** [comment]
I've been exploring some methods but they all seem to have issues.  So far I'm working on a vertical panorama stitching, but it's using image magick stuff which would be a weird dependency to add to the project.  If I get something working properly I'll try to put it out as it's own thing at this point.

**Comment by timsheng** [comment]
looking forward to new support

**Comment by msttesting** [comment]
@whiteleyj @lefthandedgoat @timsheng @KevM @charlesj 
I have tried aShot. It worked like a charm.
[Check this post](http://www.softwaretestingmaterial.com/how-to-capture-full-page-screenshot-using-selenium-webdriver/). Hope it helps.
