### ISSUE TITLE
notDisplayed Stopped working

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#340]
I apologize in advance if this was already covered, but I did search and review the previous "notDisplayed" related tickets.

I have a scenario in my application where I can add multiple profiles to one of our online applications. I go to the review page and make sure each defined user and there info appears as expected.

A followup test case is to make sure that the "Remove" user functionality works. I then delete that user, and assert that the items are no longer displaying on the page.

notDisplayed "#additionalOwnerName-0 .ng-binding"  // This is one of 8 statements

The test was working fine late last spring.  I'm dusting off the test to run in a new test environment and it fails on the "notDisplayed" commands. The app hasn't changes in all this time. I did try the ":visible" property but it didn't work for me. 

VS Error:
An exception of type 'canopy.types.CanopyNotDisplayedFailedException' occurred in canopy.dll but was not handled in user code

Additional information: notDisplay check for #additionalOwnerName-0 .link-remove:visible failed.

**Comment by lefthandedgoat** [comment]
notDisplayed has not changed in over 3 years.

Open chrome dev tools and type ```$$("#additionalOwnerName-0 .ng-binding")```

Like this and see if you get any results, if you do its because you have 1 more items with that selector
Repo the steps manually and try it before you remove something and after.  You probably have more than one dom element with that selector, or after removing the first item, the new first item (was the 2nd) now have has the same selector.

![image](https://cloud.githubusercontent.com/assets/725225/22567340/2f2d296c-e955-11e6-80dc-b77c880d9f42.png)

**Comment by sprice9161** [comment]
There are 4 users on the page, but for the sake of discussion only 2 are applicable as they are explicitly added users. The two users would appear as:
#additionalOwnerName-0 .ng-binding   // Joe Buc
#additionalOwnerName-1 .ng-binding  // Don Ocillo  (pardon my spelling)

Entering $$("#additionalOwnerName-0 .ng-binding"), returns a single span element for Joe Buc
After removing Joe Buc and entering $$("#additionalOwnerName-0 .ng-binding") again into the console. returns a single span element this time Identifying Don Ocillo.

The tool I use selectorGadget for the CSS selectors drops the parent prefix following the removal of Joe Buc, so I thought that the selector was now defaulting to " .ng-binding", but the console says differently.

I see whats happening but how can I handle it?

**Comment by lefthandedgoat** [comment]
Your app is using angular and it is generating IDs itself.  If you add a 3rd person there will be a `additonalOwnerName-2` (0 based array indexes).

You need to write a more specific css selector.  This can be challenging but it is the crux of good automation.  I just released a different chrome plugin that will help create selectors (that may or may not be exactly what you want, just guidance) that may help you.  https://chrome.google.com/webstore/detail/canopy-companion-css-sele/jehfnloleecojodohcdfpbhjahhaplje

Here is a really good cheat sheet for css and jquery selectors https://oscarotero.com/jquery/ to help you learn to write high quality ones.

**Comment by amirrajan** [comment]
>notDisplayed has not changed in over 3 years.

Confirmed that `notDisplayed` still works on a local website.

**Comment by amirrajan** [comment]
If you can @sprice9161, provide a more specific example. If you can build a simple html page with the markup that fails, I can try to diagnose a bit further. 

But specific to this issue, `notDisplayed` is indeed still working.

**Comment by sprice9161** [comment]
Closing it is fine. The example is pretty specific. I'm not sure what part you didn't get. What is happening, is that all of the additional user profiles created that appear on the screen each get a dynamically generated ID assigned to it, I don't know what the mechanism for that it. When I delete one of the profiles from the screen the remaining profiles could have their ID's changed. Where there were once 3 profiles there are now 2. So the assertion in the code is referencing the originally assigned ID, but now it has been changed.

I'll have to go to the developers to figure out how to make the ID's on this page Static. 

I'd like to give you the html markup but I'm not experienced enough yet to put that together for you, and where we are using Angular, I don't know how that would effect an example.

**Comment by lefthandedgoat** [comment]
I understand what is happening and what you need to do is learn how to write a selector that gets only the record for `Joe Buc` so that when you delete him you can check to see that he is gone.

`#additionalOwnerName-0 .ng-binding` is a selector for the first person.  That is `Joe Buc` initially but is `Don Ocillo` after you delete Joe.  

I am 99% sure that 

```
displayed "Joe Buc"
click "selector for the first remove button"
notDisplayed "Joe Buc"
```

will work.
