### ISSUE TITLE
Program execution freezes during a run ending on notDisplayed method

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#341]
I have a test case that hangs on one of the displayedAndMatches of the testcase:

        click "#nextButton"
        sleep SLEEP_INTERVAL
        click "#edit-firstOwnerName"
        "#firstOwner-ownershipPercentage" << "84"
        click "#save-firstOwnerName"
        sleep SLEEP_INTERVAL
        displayedAndMatches".highlight-text .ng-scope" "Total ownership has exceeded 100%"
        notDisplayed ".success message .ng-scope"
        notDisplayed "#ownerbutton"

I tried shifting around the last lines, also tried adding a random click onto a label but nothing seems to work. 

Debug works fine...I can step through and it exits out gracefully to program.fs Is there a command that will explicitly end the testcase and redirect to back to program.fs

My app is using Angularjs elements

**Comment by lefthandedgoat** [comment]
End the test case and exit to program so that no other tests run after?

This command will do that, put it in program.fs

https://github.com/lefthandedgoat/canopy/blob/master/tests/basictests/Program.fs#L25

**Comment by sprice9161** [comment]
No, I'd like it to move on to the next test case.

**Comment by lefthandedgoat** [comment]
It will fail the test wherever it fails and not run the rest of it, then it will move to the next test case.  Unless you are running with "test name" &&&& -> fun //whatever

For ampersands is wip mode which only runs the tests with 4 &.

**Comment by sprice9161** [comment]
I''l give it a try, but I think its just going to get stuck. I commented the testcase &&! not to run and moved onto the next one. Same thing, gets hung but will pass in debug (f10). Makes no sense.

**Comment by lefthandedgoat** [comment]
probably a timing issue.  Does it get hung there forever? and what is the error message, also what is the contents of the `displayedAndMatches` function, that is not a canopy function, that is a customer one written by someone at your work place.

**Comment by sprice9161** [comment]
Not sure if my phone reply made it...
Yes, the test does get hung forever, and does not throw an error. I'll locate the routine. I didn't consider it as this entire project was successfully run for a previous project. The only thing new is that they moved our servers and test clients to a new network.

**Comment by lefthandedgoat** [comment]
is it getting hung when running locally or on your new environment in your build/test process?

**Comment by sprice9161** [comment]
Yes, it is hanging in both environments, BUT just noticed in the Console window I'm getting a "Passed" status. Can I assume that it truly passed even if the the program won't exit the test cases to the Program.fs file?

**Comment by lefthandedgoat** [comment]
Put this line as the last line of your test

`printfn "I hit the last line"`

If it prints that, then prints "passed" then it did not freeze in the test.

Are you sure there are no lines like this `Console.Read` which would cause the the code to free there forever until a key/line is read?

Anything beyond this and you will just have to ask a developer on your team to help you.

**Comment by sprice9161** [comment]
I see the printf text in the CMD window but the program remains in the testcases. It will move onto the next testcases if I enable that test cases but gets stuck at the end of that one as well.

FYI, the custom code, when commented seems to still pass. Which is good since that passed when the routine was first implemented. 

Lets close it since the original issue of a hang isn't really the issue.

**Comment by lefthandedgoat** [comment]
If it is printing the line to the CMD window, then it is not stuck in the test case.  It may be stuck, but it is not stuck there.

In visual studio if you run the code, and it gets stuck, you can push the Pause `||` button and it will take you to the line it is stuck on.
