### ISSUE TITLE
Question: has anyone used Canopy on a site that is using NTLM authentication?

### ISSUE THREAD

**Issue by rb3003** [lefthandedgoat/canopy#342]
I have a site that pops up a modal to enter your user name a password. I believe it is using NTLM authentication. pop up can not be inspected.
My question is is there a way to configure Canopy to log into a site like this.

**Comment by lefthandedgoat** [comment]
I helped someone with it once. Not sure if it still works.  You can read about it here: https://gist.github.com/lefthandedgoat/ef20c7843e021a4f93c4

**Comment by rb3003** [comment]
Thanks for the quick reply. Unfortunately this did not work for me. However, I did find a less than ideal, old school, solution. 
Configure your url like this...
http://{username}:{password}localhost
It will log you in just fine. This is not ideal since you're sending your username and password in the URL. So, it might not be a great solution for some. For me it works for two reasons. One, the test are run internally by a Dev or QA. Two, the site is internal, behind our firewall.
Hope this helps someone else.

**Comment by lefthandedgoat** [comment]
Sorry to hear it but I am glad you found a working solution.

Unfortunately in browsers, you can not control that pop up box asking for user information.  Only Alert boxes.
