### ISSUE TITLE
Timing Issues: Inconsistent failures while executing the test suite

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#343]
I'm executing a test suite (a single test_xxx.fs file) containing 10 test cases, with one marked for omission "&&!".  Each time I execute, I get a different failure from a different test. I've already gone through isolating, debugging and rerunning the failing test, only to watch it pass. We have discussed Angular element previously, and Canopy is supposed to support it, with its known timing issues. I'm not saying that its an Angular issue but it is the first thing that jumps to mind. I don't think that its an issue of the element not being there but more of the script maybe getting out of sync, I don't explicitly define "elementTimeout", so I'm assuming that the default value of 10 sec is active. Some failures show up as fields that were not populated and others as elements not found, but either way it seems to be a timing issues. Any suggestions. I've already tried "&&&&&" mode. I want these tests to eventually run headless.

**Comment by lefthandedgoat** [comment]
Read the error messages.  I spent a lot of time making them friendly and useful. If the error message says that an element is not there, then it is not there.

You can run in WIP mode "&&&&" which will run the tests slower, so you can 'debug with your eyes'

I have had tests fail only ~10% of the time because of real bugs.  The bugs didn't happen 100%.

**Comment by sprice9161** [comment]
I must not be explaining correctly. Here is an example that I just ran. This time Test Cases 4 failed.

        "#additionalOwner-firstName1" << "Don" 
        "#additionalOwner-lastName1" << "Orsillo" 
        "#additionalOwner-addressSelection1" << "Same address as Joe Buck"
        "#additionalOwner-phoneNumber1" << getRandomPhoneNum
        "#additionalOwner-email1" << "QAAutomation1@directcapital.com"
        "#additionalOwner-dateOfBirth1" << "12/16/1968"
        "#additionalOwner-ownershipPercentage1" << "33" 
        
        click "#nextButton"

        click "#additionalOwnerName-0 .link-remove" 

The canopy exception, applies to the last line:
An exception of type 'canopy.types.CanopyElementNotFoundException' occurred in canopy.dll but was not handled in user code

Additional information: can't find element #additionalOwnerName-0 .link-remove

The failure occurred because as the page was being populated,  "#additionalOwner-firstName1" << "Don"  failed to populate. So that when  click "#nextButton" is executed, the page fails and therefor does not proceed to the Review page.  The canopy error occurred because click "#additionalOwnerName-0 .link-remove" is expecting to click on a link that is on the Review Page, and since it was never loaded....

So yes, the canopy message tells you what it sees as a failure, but that doesn't help me with the intermittent  issue that I'm attempting to describe.

**Comment by lefthandedgoat** [comment]
Add this in your helper library

```
let ( <<< ) selector text = 
    wait 5.0 (fun _ ->
        selector << text
        read selector === text
        true)
```

And switch the part of your test that sometimes fails to write to use `<<<` instead of `<<`
