### ISSUE TITLE
Send HTML report after tests are completed

### ISSUE THREAD

**Issue by adalenthya** [lefthandedgoat/canopy#344]
If you can, please help me out on this one, I have little experience with F#
I know it's not Canopy related, but F# related.

I created a function that is sending via email a report from the directory containing my Canopy reports.
But it is sending the email before my tests are completed and before the current report is generated.
So it's sending the previous report, not the newly created one.

`namespace YSI.CC.Canopy.Library

module Email =

    open System.Net.Mail
    open System.IO
    open System.Net
    open YSI.CC.Canopy.Library.CommonUtilities

    let SendMail (emailSubject : string, emailBody : string) =  
        let mail = new MailMessage(); 
        mail.From <- new MailAddress(AppConfig.FromEmailAddress,"Commercial Cafe Automation Alert"); 
        mail.To.Add(AppConfig.ToEmailAddress4); 
        mail.Subject <- emailSubject
        mail.Body <- emailBody; 
        

        mail.Attachments.Add(new Attachment(ILSFilePath()))
 
        let client = new SmtpClient(AppConfig.SMTPServerName,25); 
        
        try 
        ( 
            client.UseDefaultCredentials <- true    
            client.Send(mail) 
            printfn "Email Send Successfully"         
        ) 
        with 
           | ex -> printfn "Email Sending Failed.\n\n%s" ex.Message        
        0
`
 
"ShowDashboard()" contains all my tests and "SendMail (..)"

`module Program

open canopy
open runner
open System
open configuration
open reporters
open YSI.CC.Canopy.Library.CommonUtilities
open YSI.CC.Canopy.Library

ILSDashboard.ShowDashboard()

configuration.chromeDir <- AppConfig.ChromeDriverPath
reporter <- new LiveHtmlReporter(Chrome, configuration.chromeDir) :> IReporter  
let liveHtmlReporter = reporter :?> LiveHtmlReporter
liveHtmlReporter.reportTemplateUrl <- AppConfig.WebReportURL
let path = AppConfig.HtmlReportPath + "ILS/ILS_Report-"  + System.DateTime.Now.ToString("MM-dd-yy-H-mm-ss")
liveHtmlReporter.reportPath <- Some path

run()
quit() 
`

Not sure how to send the email after the report is generated.

**Comment by lefthandedgoat** [comment]
The report wont be done and populated until after `run()` for sure, and possibly after `quit`

Maybe move the SendMail call out of ShowDashboard and call it at the bottom.

**Comment by adalenthya** [comment]
It worked, thank you so much! I

**Comment by lefthandedgoat** [comment]
No problem!
