### ISSUE TITLE
Support for `addSelection` or some workaround for PhantomJS?

### ISSUE THREAD

**Issue by vilinski** [lefthandedgoat/canopy#349]
Hi,

my wish where to select multiple options in one select element. The seleniums 'addSelection' is currently not supported by canopy. I found a workaround working for chrome with `ctrlClick`:

```fsharp
let (<<<) select (values: string list) =
    values
    |> List.iter(fun value -> element select |> elementWithin (string value) |> ctrlClick )

"#mySelectElem" <<< ["123"; "Milk"; "Water"]
```

But this doesn't work with PhantomJS, which has some problems with modifier keys. Needed for headless testing.

**Is there any other ways how to accomplish this?**

Thx

**Comment by lefthandedgoat** [comment]
You can access anything Selenium can do via `browser`.  It is an instance of IWebDriver and should have `addSelection`

Tonight I can look into it more and see if I can provide a convenience method for you.

**Comment by lefthandedgoat** [comment]
Can you use the code you already have, but instead of `ctrlClick` just use `click` ?

For me this code will select two items in a multi select, but I don't have phantom setup to confirm.

```
url "http://lefthandedgoat.github.io/canopy/testpages/"

let el = element "#multi"
elementWithin "Small" el |> click
elementWithin "Large" el |> click
```

**Comment by vilinski** [comment]
Thank you! Didn't know click is enough.
Confirm it works for me on mono+mac with your test pages in chrome and in PhantomJS too.
Will test tomorrow with my test page.

**Comment by lefthandedgoat** [comment]
Excellent!
