### ISSUE TITLE
TeamCity reporter shows skipped tests as passed instead of ignored

### ISSUE THREAD

**Issue by galatrash-at-dnn** [lefthandedgoat/canopy#350]
Please change the TeamCity reporter to report skipped tests as being **ignored** and not passed.

Here is the scenario I use: I begin with a test that installs a full web site and if it fails I set:
``canopy.configuration.skipAllTestsOnFailure <- true``
so that all subsequent tests are ignored and bypassed. But TeamCity shows something like this:
`` Tests failed: 1, passed: 99 ``
which is misleading. The right thing to show is something like this:
`` Tests failed: 1, ignored: 99 ``

**Comment by lefthandedgoat** [comment]
Do you have this part backwards?

```
 But TeamCity shows something like this:
Tests failed: 1, passed: 99
which is misleading. The right thing to show is something like this:
Tests failed: 1, ignored: 99
```
I think now it would show `failed: 1, ignored: 99` but you want it to say `passed` I think?

I can do this, but `skip` in canopy is the same as the `Ignore` attribute in nUnit etc, in that it does not run the test.  Team city does not have a skip, they have Pass, fail, and ignore and in my opinion ignore is the match of the given choices.

I can try to make something work for you, but I need to figure something out that doesn't break backward compat.

**Comment by galatrash-at-dnn** [comment]
I need TeamCity to show ``ignored``.

Maybe you can add a flag (e.g.,  ``reporter.showSkippedAsIgnored``) which by default has backward compatibility and it can be changed to show ignored.

**Comment by lefthandedgoat** [comment]
Ok, showing ignored is the correct thing.  If it is not it is a bug, so I do not need to focus on backwards compat.

You can see here that it is writing ignored to the console, but if it is not working I will figure it out.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs#L180

Can you tell me what version of TeamCity you are using?  I will get it installed and repro and fix.

Thanks!

**Comment by galatrash-at-dnn** [comment]
I'm using the latest: TeamCity Enterprise 10.0.4 (build 42538)

BTW, you can see a sample of this case here (use "login as guest"):
http://dev-build1:8088/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=716818#_focus=899

**Comment by lefthandedgoat** [comment]
This is fixed in the latest version of canopy that you can download here: https://www.nuget.org/packages/canopy/1.2.0

**Comment by galatrash-at-dnn** [comment]
It is working properly now. Thank you.
