### ISSUE TITLE
Selenium webdriver constraint

### ISSUE THREAD

**Issue by onionhammer** [lefthandedgoat/canopy#351]
Something is fishy with the nuget package, where Selenium.WebDriver (installed because its a dependency of canopy) wants to update to 3.3.0, but canopy has a constraint set to =3.0.0

**Comment by lefthandedgoat** [comment]
Its like that in purpose because in the past I think there were new versions of selenium that did not work with canopy until I compiled canopy against them, so I pinned it.  I can update to 3.30 and push a new build.  Probably tomorrow because I may have one more change to go with it.

**Comment by onionhammer** [comment]
Hmm. seems like nuget shouldn't present it as an available update and then fail upon trying to update because of constraints..

**Comment by lefthandedgoat** [comment]
Yah I just opened up VS and saw what you are talking about.  It is in the update tab but fails to update.  I can't control that but I will push a new build out with the latest Selenium.

**Comment by lefthandedgoat** [comment]
You can downloaded the latest canopy that uses Selenium 3.3.0 and I also removed the restraint.

You can download it here: https://www.nuget.org/packages/canopy/1.2.0
