### ISSUE TITLE
Is it possible to hide drivers console window?

### ISSUE THREAD

**Issue by Ma3yTa** [lefthandedgoat/canopy#352]
I run canopy under gui application and I want to hide console.
Is it possible?

**Comment by Ma3yTa** [comment]
Please add option to configuration to hide console window

http://stackoverflow.com/questions/11501623/chromedriver-console-application-hide

**Comment by Ma3yTa** [comment]
done in this PR https://github.com/lefthandedgoat/canopy/pull/353

**Comment by lefthandedgoat** [comment]
The code in the PR was not working for me in Windows 10 or OSX.  I have fixed it, but I was not getting chrome driver consoles popping up, so I was not able to test that the flag actually works.

**Comment by lefthandedgoat** [comment]
Associated commit : https://github.com/lefthandedgoat/canopy/commit/6a4c5f279f5d96b697312c3d8e8228391d767c58

**Comment by Ma3yTa** [comment]
I checked. I don't see chrome driver console when set ``hideCommandPromptWindow <- true``. Thanks

**Comment by lefthandedgoat** [comment]
You can download the latest nuget with your changes here: https://www.nuget.org/packages/canopy/1.2.0
