### ISSUE TITLE
System.TypeLoadException: 'Could not load type 'canopy.core' from assembly

### ISSUE THREAD

**Issue by neatville** [lefthandedgoat/canopy#357]
... 'Canopy, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'

Visual Studio 2017. 

This is after I run the example right on the homepage for canopy. I see no red squiggly lines in the code.

**Comment by lefthandedgoat** [comment]
I will have to create a VM to try to reproduce this, so it may be a while.  I suspect it has something to do with binding redirects =(

**Comment by lefthandedgoat** [comment]
I just installed VS 2017, adding only F# support and everything worked.

Could you possible put your code on github so I can make sure all the settings are correct?

Also, what operating system?  Windows 10?

**Comment by neatville** [comment]
Sorry for the long delay. I just tried it again, same thing. Yes, Windows 10 Home edition inside of VirtualBox.  
```
open canopy
open runner
open System
// Learn more about F# at http://fsharp.org
// See the 'F# Tutorial' project for more help.
start chrome

"take canopy for a spin" &&& fun _ ->
    url "http://lefthandedgoat.github.io/canopy/testpages/"

    "#welcome" == "Welcome"

    "#firstName" == "John"

    "firstName" << "Something Else"

    "#button_clicked" == "button not clicked"

    click "#button"

    "#button_clicked" == "button clicked"

run()

printfn "press [enter] to exist"
System.Console.ReadLine() |> ignore

quit()
```

**Comment by amirrajan** [comment]
I have access to a Windows 10 box. I'll give it a shot Monday.

**Comment by lefthandedgoat** [comment]
Also, is this a console application or an .fsx script?

**Comment by WalternativE** [comment]
I encountered the same problem using Windows 10 and Visual Studio Code.
I assume that the .fsx script Variant with a simple paket reference on canopy isn't supported - is this correct?

**Comment by lefthandedgoat** [comment]
It should work with fsx and paket.

Try setting the paket to .net 452 or 4.6 like this: https://github.com/lefthandedgoat/canopy/blob/master/paket.dependencies#L3

**Comment by WalternativE** [comment]
I found the error! I did not reference the WebDriver.dll in my .fsx script. I assume that some weird kind of exception masking must have happened when it didn't find the dependet assembly in the fsi context.

I executed the getting started example using the chrome driver and it worked like a charm. Thanks a million for the help :)

**Comment by lefthandedgoat** [comment]
Excellent!

**Comment by amirrajan** [comment]
@WalternativE take a look at the zip file here: https://github.com/lefthandedgoat/canopy/issues/385
