### ISSUE TITLE
Support for chrome headless?

### ISSUE THREAD

**Issue by onionhammer** [lefthandedgoat/canopy#366]
Any changes needed to support this? Rumor has it phantomjs is no longer getting updated because of this.

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by lefthandedgoat** [comment]
I think you just send an additional option, so no changes needed if you use https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L849

I can also add a helper to do it, once it becomes the main version and I can easily test it.

I didnt see any mention of Selenium testing in the post, but I suspect it will 'just work'

**Comment by Ma3yTa** [comment]
https://dzone.com/articles/running-selenium-tests-with-chrome-headless it is already available in version 59

**Comment by vilinski** [comment]
Works with latest chrome driver: 2.30. Other than chrome with "--headless" option shows a white window now and takes white screenshots :) Dunno whether it's a correct behavior.

**Comment by lefthandedgoat** [comment]
Added `ChromeHeadless` start mode that adds the right options for you.  Seems to work well except screenshots are not working.  Its a known issue with the chrome team

https://www.nuget.org/packages/canopy/1.5.1

**Comment by vmandic** [comment]
Hi. Is this option still available with latest 2.0.1 and Chrome? Can we take screenshots now with headless also? Thanks.

**Comment by lefthandedgoat** [comment]
@vmandic  yes you can still do `start ChromeHeadless`.  I have never tried taking a screenshot with headless but you can try.
