### ISSUE TITLE
Error: Loading of unpacked extensions is disabled by the administrator

### ISSUE THREAD

**Issue by sprice9161** [lefthandedgoat/canopy#369]
Ref: https://bugs.chromium.org/p/chromedriver/issues/detail?id=639#c26

I can't successfully launch any canopy scripts with Chrome (V58)/Chromedriver (2.29). Our group just got new laptops replacing our desktops and we are now configured with the latest versions. I have white-listed extensions on my chrome installation, some packed, some unpacked, but since the directory names are randomized I can't really which is which. I get "Error Loading Extension":"Failed to load extension from C:\User\... Loading of unpacked extensions is disabled by the administrator"

I'm currently working with our it group but if my extensions are already white-listed, then I'm not sure what the issue is. I've tried multiple chrome driver options.

Running a script through soapUI (scripting test step) allows me access to the popup box when the script executes, where I retrieved the error message and located the ticket above (see the link). By passing the chromeoptions in my script, the browser window will launch but the popup still appears. Clicking twice on the popup closes it, and allows the browser to navigate to the specified location. However there seems to be no chromedriver options that are successful in suppressing the popup. 

Has any of this come to your attention? Is is something that you would look into and work on or is it a chrome or chromedriver issue, or is it simply working as designed and it becomes an IT policy issue?

**Comment by lefthandedgoat** [comment]
I honestly do not know, its probably a chrome + policy issue.

**Comment by sprice9161** [comment]
I don't believe its canopy related. I was hoping that someone here has run into it. If fails from VS running Canopy, and it also fails from soapUI where I have imported and configured Selenium to run. So I don't believe that any tool has anything to do with it. One of the threads that I read said that the found a working combination of Chrome v56 and ChromeDriver v2.27, but that still fails for me. Would you happen to know what versions you and others are successfully working with? 

If your at all interested. There seems to be a difference when launching from a script. This doesn't happen when I launch standalone, which is strange since that is where you can see all of the unpacked and packed extensions. Launching through the script, the extensions page is empty.

Anyway, not trying to pull you into it, but it you know of a working combination that would be helpful.

**Comment by lefthandedgoat** [comment]
When you launch from code, it will launch a browser in 'incognito mode' which loads no extensions, cookies, history etc.

Latest chrome and chromedriver should work, but you will have to read on how to load extensions when you launch chrome.  I have not done it (but it is possible).

**Comment by sprice9161** [comment]
The latest is the one being reported online and has the ticket entered that I referenced. At the moment I don't really care about loading extensions, I just want to launch a browser...

Thanks for the response. If you do hear from other users, could you please update the ticket?

**Comment by lefthandedgoat** [comment]
You are the only person that I have heard this from.  I suspect that when you got new laptops, they were set up differently (in terms of windows permissions/group policies) and that is causing the problem for you.

**Comment by sprice9161** [comment]
Chris, thank you for your suggestion. I found someone in dev with a non standard laptop and loaded the scripts onto his machine. They are working. No popup no errors. I'll be meeting with the security team. Huge help, thank you for you thoughts on this.
