### ISSUE TITLE
Incognito

### ISSUE THREAD

**Issue by simax** [lefthandedgoat/canopy#370]
Is it possible to start chrome in **incognito** mode?

**Comment by lefthandedgoat** [comment]
You can launch chrome and provide any custom options you like, and after some googling it looks like there is one for incognito

```
let chromeOptions = OpenQA.Selenium.Chrome.ChromeOptions()
chromeOptions.AddArgument("--incognito")
start <| ChromeWithOptions chromeOptions
```

worked for me

**Comment by simax** [comment]
I think that should work but unfortunately I'm getting the following error:

```
System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in WebDriver.dll
Additional information: unknown error: No current window
JavaScript stack:
Error: No current window
    at checkForExtensionError (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:14:17)
    at Object.callback (chrome-extension://aapnijgdinlhnhlmodcfapnahmbfebeb/background.js:67:5)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:74:7)
  (Session info: chrome=58.0.3029.110)
  (Driver info: chromedriver=2.30.477700 (0057494ad8732195794a7b32078424f92a5fce41),platform=Windows NT 10.0.10586 x86_64)
```
I'm using `ChromeDriver version  2.30.477700`. Looks like it's reported [here](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1083). I tried adding `chromeOptions.AddArgument("--enable-automation")` as suggested but it didn't help.

**Comment by lefthandedgoat** [comment]
Do you need to be in incognito mode?

When you launch a new browser the standard way, it has no extensions, no browsing history, and no cookies, so its very similar.

Whats your general objective/need?

**Comment by lefthandedgoat** [comment]
Also, I did some googling, and that error happens when you try to resize an incognito browser, which canopy does automatically.

This worked w/o errors for me.

```
configuration.autoPinBrowserRightOnLaunch <- false

let chromeOptions = OpenQA.Selenium.Chrome.ChromeOptions()
chromeOptions.AddArgument("--incognito")
start <| ChromeWithOptions chromeOptions
```

**Comment by simax** [comment]
Thanks, adding `configuration.autoPinBrowserRightOnLaunch <- false` did the trick!
