### ISSUE TITLE
Consider moving this to FSharp GH Organization?

### ISSUE THREAD

**Issue by amirrajan** [lefthandedgoat/canopy#373]
Maybe move this over to FSharp.org GH Org and call it FSharp.WebUIAutomation?

**Comment by lefthandedgoat** [comment]
Why

**Comment by amirrajan** [comment]
Mostly visibility, may get it "blessed" too.

**Comment by lefthandedgoat** [comment]
I think I remember Don saying one time its good to have stuff outside of that org also so it doesn't look like blessed vs not blessed.

I also think Forki or someone asked me a long time ago but I didn't feel worthy lol.

**Comment by amirrajan** [comment]
Closing it (wanted to have an artifact that it was at least talked about (personally I like LeftHandedGoat.Canopy as a namespace).
