### ISSUE TITLE
"Did you mean" hint points to the element that was not found...

### ISSUE THREAD

**Issue by knocte** [lefthandedgoat/canopy#374]
We've just had a test fail this way:

```
Couldn't find any elements with selector '#publicinboxfield', did you mean:
	#publicinboxfield
	#publicInboxCtrl
	#public_tab
	Pricing
	#public_showmaildiv
```

How can this be possible? I thought that the list of suggestions would be gathered from the elements that are currently in the webpage, but if this is true, then the element was already there and should have been found.

**Comment by knocte** [comment]
(BTW we're using version 1.0.1)

**Comment by lefthandedgoat** [comment]
The only thing I can think of is that the element was not there, then when it ran the code to grab all the elements it showed up.  Like a race condition kind of.

Can you attach a screenshot of chrome's inspector window looking at that element?

Also you may want to upgrade versions.  You have to keep your selenium versions synced with browser versions because things will stop working as versions tick up.

**Comment by knocte** [comment]
> You have to keep your selenium versions synced with browser versions because things will stop working as versions tick up.

If you use a stable distro version, browsers versions are stable as well, so no issue here (we use chromium BTW).

**Comment by knocte** [comment]
> then when it ran the code to grab all the elements it showed up. Like a race condition kind of.

Then the code that scans the page to grab suggestions should be self-healing and optionally return the originally-searched element :)

**Comment by lefthandedgoat** [comment]
Does this fail every time or just happened one time?

**Comment by knocte** [comment]
Just once.

**Comment by lefthandedgoat** [comment]
Oh, then it would be reasonable to remove the selector from the suggestions, because it really was just a race condition.

Will do, thanks!

**Comment by knocte** [comment]
> to remove the selector from the suggestions

I'd prefer returning it if it's found :) (I know, maybe this fix would be more complex...)

**Comment by lefthandedgoat** [comment]
Never got around to this because its a lot of work =(

**Comment by l3m** [comment]
This seems to be a problem still, I get such errors for a field that is populated only after a request: 

Couldn't find any elements with selector 'Design Engineer', did you mean:
    Design Engineer
	#select-single-vt
	.shadow-inner

**Comment by lefthandedgoat** [comment]
@l3m Do you have a small test to reproduce against a public site?
