### ISSUE TITLE
Screenshots are black in the Canopy Html report received via Email, as an attachment

### ISSUE THREAD

**Issue by adalenthya** [lefthandedgoat/canopy#377]
This is a recent issue, I noticed the screenshot are black in the Canopy Html report:
![2017-07-24 12_15_22-ysi cc canopy ils - microsoft visual studio](https://user-images.githubusercontent.com/23504299/28516463-0461f3ce-706a-11e7-94c6-1bf4b0cc70f4.png)
No idea why this is happening.

**Comment by adalenthya** [comment]
Seems to be happening only when opening the report received via email. I am sending the reports to various recipients and when viewing it, it doesn't show the screenshots.

**Comment by lefthandedgoat** [comment]
Can you email them to me? Username at gmail

**Comment by adalenthya** [comment]
I forwarded you the exact email that contains the report.

**Comment by lefthandedgoat** [comment]
If you grab a copy of it before it is sent does it work?  The image is a weird repeating series of characters and I am wondering if the email server or some anti virus is modifying the content.

Also, did this work in the past?  If so can you make sure that your chromedriver version is in line with your chrome version?

https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by adalenthya** [comment]
Yes, the report is also saved locally before sending it, and it works great. 
It might have something to do with the email server. I will use a gmail address and see if it works ok.
The chrome-driver version is 2.29, i don't think it may be related.
Yes, it did work in the past, with the same email.
