### ISSUE TITLE
Why can't keep developer tool open?

### ISSUE THREAD

**Issue by jenniferdnn** [lefthandedgoat/canopy#378]
Is there any special reason canopy force close the developer tool?
I am thinking to provide a way to save the har file. 
First thing noticed is the F12 is not supported. And second is canopy will close the developer tool right after click an element. 

Will you consider to provide a way to press F12 and open network tab?

**Comment by lefthandedgoat** [comment]
Thats a selenium/chrome thing.  I think chromedriver controls the browser via chrome tools, so having it open causes conflicts.

I googled for a way to have selenium save a HAR file but did not see anything.

canopy uses selenium under the hood and you can access it with the `browser` value.  `browser.GetElements(...)` etc, so if you do find an example online you can use that.

**Comment by jenniferdnn** [comment]
I checked on java, selenium doesn't close the developer tool. I am not sure it is closed by canopy or something else. Thanks. Just feel open the door for developer is better than closing the door.  To avoid conflicts, there are many ways. Such as default setting, and so on.

**Comment by lefthandedgoat** [comment]
Interesting.  And this is Java using selenium?

The chromedriver page suggests that it should be closing.

https://sites.google.com/a/chromium.org/chromedriver/help/devtools-window-keeps-closing

**Comment by jenniferdnn** [comment]
Tried on firefox and selenium in java code.

**Comment by jenniferdnn** [comment]
It is fine, Thanks lefthandgoat, I am studying other solutions.

**Comment by lefthandedgoat** [comment]
If it works in Firefox in Java then it should also work in Firefox with canopy.  I thought you were referring to chrome dev tools in your original question.

If you were talking about Firefox I can try to reproduce.  I havent used selenium and firefox in years.

**Comment by jenniferdnn** [comment]
I haven't try on java with chrome, but using canopy on firefox and chrome, it is closing the developer tool. But I am new to f#, canopy. I am not sure it is the webdriver or canopy.

**Comment by lefthandedgoat** [comment]
For chrome its chrome, not f# or canopy.  I will try Firefox tonight and let you know what I learn.

**Comment by lefthandedgoat** [comment]
I was able to open dev tools in Firefox and it stayed open as tests ran.  See below:

![image](https://user-images.githubusercontent.com/725225/29420757-8b8e6ba8-8338-11e7-9525-50dfe2496f0e.png)

**Comment by jenniferdnn** [comment]
I tried also. You are right, it works on firefox. My fault. I guess I tried at that moment it is chrome. Sorry and thank you so much.
