### ISSUE TITLE
Markdown to Canopy?

### ISSUE THREAD

**Issue by amirrajan** [lefthandedgoat/canopy#382]
Users updates a markdown file available at some endpoint.

Canopy can read the markdown file and construct a test suite from it? 

Maybe with the following format:

| name     | css              |
| -        | -                |
| email    | `#email_field`   |
| password | `#password_field`|
| login    | `#login_button`  |

1. type "user@example.net" into `email`
2. type "qwerty" into `password`
3. click `login`

It would take the markdown and create the canopy file.

The markdown above would create well formed html, so I'm assuming it'd be easy to parse.

Here is the raw html from the format above:

```html
<table>
  <thead>
    <tr>
      <th>name</th>
      <th>css</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>email</td> <td><code>#email_field</code></td>
    </tr>
    <tr>
      <td>password</td> <td><code>#password_field</code></td>
    </tr>
    <tr>
      <td>login</td> <td><code>#login_button</code></td>
    </tr>
  </tbody>
</table>

<ol>
  <li>type "<a href="mailto:user@example.net">user@example.net</a>" into <code>email</code></li>
  <li>type "qwerty" into <code>password</code></li>
  <li>click <code>login</code></li>
</ol>
```

**Comment by lefthandedgoat** [comment]
I think you would need to provide an action column too.  How do I know to read/write/click

**Comment by amirrajan** [comment]
I’d say the first word (action) of every ‘li’ is reserved by canopy. It’s either supported or not

**Comment by lefthandedgoat** [comment]
Oh, didnt see the list of actions below. sorry.

**Comment by amirrajan** [comment]
Closing for now. Just an idea, but probably too limiting.
