### ISSUE TITLE
Missing method exception when updating Selenium to 3.5.2

### ISSUE THREAD

**Issue by forki** [lefthandedgoat/canopy#383]
Taking screenshot to D:\Work\835a948d\0\products\msu.Reading\temp\screenshots\Termin �ndern.png
    [16:10:52 ERR] All tests/Z�hlerwechsel/Termin �ndern errored in 00:02:16.1270000 <Expecto>
    System.MissingMethodException: Methode nicht gefunden: "Void OpenQA.Selenium.Screenshot.SaveAsFile(System.String, System.Drawing.Imaging.ImageFormat)".
       bei canopy.mobile.core.screenshot(String path, String fileName)
       bei msuReading.IntegrationTests.ExpectoHelper.testCase@12.Invoke(Unit unitVar0)
       bei Expecto.Impl.execTestAsync@859-1.Invoke(Unit unitVar)
       bei Microsoft.FSharp.Control.AsyncBuilderImpl.callA@839.Invoke(AsyncParams`1 args)

**Comment by forki** [comment]
I get this error with Canopy.Mobile but I assume it's similar here.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/30263224-59c43b3e-96d4-11e7-99f3-489cc2bf08d1.png)

**Comment by lefthandedgoat** [comment]
Ok I will look into it!

**Comment by lefthandedgoat** [comment]
Nope not an issue in regular canopy.  I don't use that method.

Were you able to resolve the problem in canopy.mobile?

**Comment by forki** [comment]
Yes. All is well then. Thanks
