### ISSUE TITLE
load test improvements

### ISSUE THREAD

**Issue by lefthandedgoat** [lefthandedgoat/canopy#390]
Print baselines, sorted by task
Sort by task name when printing results
Use defined function for determining if something crossed threshold
print job stats
print the frequency in the task desc

**Comment by amirrajan** [comment]
Write all the things to STDOUT and let some other thing do all this ^

**Comment by lefthandedgoat** [comment]
Its not unreasonable to do 1000s of request in a load test which would maybe be too much noise?

I am printing all of the results tho to console.

**Comment by lefthandedgoat** [comment]
Done except `Use defined function for determining if something crossed threshold`
