### ISSUE TITLE
Check a box based on an independent span on the same row

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#391]
Is there a way to check a box based on an independent span on the same row?

**Comment by lefthandedgoat** [comment]
If you can give me a snippet of the html I can help you write a selector

**Comment by rodsantest1** [comment]
I may have fibbed a bit, there are no spans...

<table>
  <tbody>
    <tr>
      <td>
        <input type="checkbox" />
      </td>
      <td>Target 1</td>
    </tr>
    <tr>
      <td>
        <input type="checkbox" />
      </td>
      <td>Target 2</td>
    </tr>
    <tr>
      <td>
        <input type="checkbox" />
      </td>
      <td>Target 3</td>
    </tr>
  </tbody>
</table>

**Comment by rodsantest1** [comment]
sorry about that.

**Comment by lefthandedgoat** [comment]
`"//td[text()='Target 1']/../td[1]"`

That will get the first TD of the row that has a TD with text of 'Taget 1'

its an xpath selector and the breakdown of each part is

// = anywhere in doc
td = find a td
[text()='Target 1'] = with a text property equal to Target 1
/.. = find its immediate parent
/td[1] = find the immedate tds and get the [1]th item

If you have checkboxes a more specific one may be

`"//td[text()='Target 1']/../td/input[text='checkbox']"`

Hope this helps!

**Comment by rodsantest1** [comment]
Thanks for the help! Also, thanks for abstracting Selenium plumbing with canopy. I'll definitely help spread the word! Please keep it up :+1:
