### ISSUE TITLE
Is there a way append text to an input textbox?

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#392]
Is there a way append text to an input textbox?

For example, when I'm editing a record, can I take a textbox by its xpath and append to its existing value and re-save the record?

I tried this:
`"/html/body/form/table/tbody/tr[2]/td[2]/input" <<  "edited" + sprintf "%s" "/html/body/form/table/tbody/tr[2]/td[2]/input"`

**Comment by lefthandedgoat** [comment]
You can turn on this configuration `optimizeByDisablingClearBeforeWrite` but that would change the behaviour for everything.

You could also do 

`"/html/body/form/table/tbody/tr[2]/td[2]/input" << read "/html/body/form/table/tbody/tr[2]/td[2]/input" + "edited"
