### ISSUE TITLE
Click delete link however many variable rows there are

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#395]
I have a variable amount of `<tr>` rows that I'd like to delete using delete link in each row.

How can I achieve this without hard-coding the number of rows to delete?

**Comment by lefthandedgoat** [comment]
the `click` command will attempt to click every instance of a selector on the screen.  It really depends on the behaviour of your application.  If its just removing them from the UI it 'should' work.  If its taking you to a new screen, or re-loading the existing screen it will probably only be able to click the first one before the page redirect happens.
