### ISSUE TITLE
Confusing behaviour of many

### ISSUE THREAD

**Issue by Wkalmar** [lefthandedgoat/canopy#397]
Hi, I'm not sure whether my report is valid because I've didn't function `many` in your [documentation](https://lefthandedgoat.github.io/canopy/)
Nevertheless, it is pretty weird, otherwise would be very powerful. I'll illustrate what I mean with following snippets:

```fsharp
"Many test" &&& fun _ -> //this one is executed
    url "http://sokker.org/"
    "#ilogin" << <my login here>
    "#ipassword" << <my pass here>
    click "button[type='submit']" 
    many 100 (fun _ -> url "http://sokker.org/player/PID/35820470") //but this not

run()
```

It gets even weirder when I extract it from my test like this:

```fsharp
"Many test" &&& fun _ -> //this one is not executed
    url "http://sokker.org/"
    "#ilogin" << <pass>
    "#ipassword" << <login>
    click "button[type='submit']"    

many 100 (fun _ -> url "http://sokker.org/player/PID/35820470") //this one does

run()
```

Also, I was wondering: the signature of `many` goes like this int -> f(unit -> unit) -> unit which basically means to me that I can't pass any parameter inside f. To me it would be quite more useful int -> f(int -> unit) -> unit to be able to perform smth like this
`many 100 (fun count -> url (String.Format("http://sokker.org/player/PID/{0}", 35820470+count)))`
Thanks in advance for your answer to both questions!
Best regards,
Bohdan

**Comment by lefthandedgoat** [comment]
Many is there to run the same test many times.  Generally so you can make sure that everything is stable and you don't have failures on occasion.

You should write your test like this

```
many 10 (fun _ -> //this one is executed
    url "http://sokker.org/"
    "#ilogin" << <my login here>
    "#ipassword" << <my pass here>
    click "button[type='submit']" )
    on "your landing page"
```

And that wil login you 10 times.

If you want a version of many that will take a function that also has the iteration in it you can use this

```
let many2 count (f : int -> unit) = 
  [1..count] 
  |> List.iter (fun i -> sprintf "many test %i" i &&& fun _ -> f i)
```

This will create many normal tests that take a function using the iteration, instead of a normal `unit -> unit` function

Hope this helps!

**Comment by Wkalmar** [comment]
Thanks, you've helped a lot
