### ISSUE TITLE
dynamic test environment receiving some messages in console

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#398]
Hey, I have a dynamic test environment where even the browsers are installed on the fly. It's on a VM that gets wiped pretty often.

I was testing on Chrome and got the following log in the console. Just wondering if any of it made sense because doesn't to me immediately. If not, no worries.

> Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on
> port 49419
> Only local connections are allowed.
> 
> DevTools listening on ws://127.0.0.1:12471/devtools/browser/337e3d14-d729-4a07-8
> 973-bc4bfe85cdf2
> [3996:4580:1212/111731.818:ERROR:service_manager.cc(157)] Connection InterfacePr
> oviderSpec prevented service: content_renderer from binding interface: blink::mo
> jom::ReportingServiceProxy exposed by: content_browser
> [3996:4580:1212/111808.981:ERROR:service_manager.cc(157)] Connection InterfacePr
> oviderSpec prevented service: content_renderer from binding interface: blink::mo
> jom::ReportingServiceProxy exposed by: content_browser
> [3996:4580:1212/111809.911:ERROR:service_manager.cc(157)] Connection InterfacePr
> oviderSpec prevented service: content_renderer from binding interface: blink::mo
> jom::ReportingServiceProxy exposed by: content_browser
> [3996:4580:1212/111926.147:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
> [3996:4580:1212/111926.147:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
> [3996:4580:1212/111926.147:ERROR:process_metrics.cc(105)] NOT IMPLEMENTED
> Starting ChromeDriver 2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f) on
> port 51701
> Only local connections are allowed.
> 
> DevTools listening on ws://127.0.0.1:12117/devtools/browser/c29622e2-eab1-4784-b
> 44d-47c2920b3c4f
> [6876:1640:1212/112018.940:ERROR:service_manager.cc(157)] Connection InterfacePr
> oviderSpec prevented service: content_renderer from binding interface: blink::mo
> jom::ReportingServiceProxy exposed by: content_browser

**Comment by lefthandedgoat** [comment]
Generally these are debug messages by/from chrome and chromedriver.  As long as things are still working I would not worry about them.

If things are broken try updating both chrome and chrome driver to latest, or reverting chrome to a previous version.

**Comment by rodsantest1** [comment]
Yeah, everything seems to be working despite those messages. Thanks Chris, I'll close it out when I get back from lunch.

On Dec 12, 2017, at 11:39 AM, Chris Holt <notifications@github.com<mailto:notifications@github.com>> wrote:


Generally these are debug messages by/from chrome and chromedriver. As long as things are still working I would not worry about them.

If things are broken try updating both chrome and chrome driver to latest, or reverting chrome to a previous version.
