### ISSUE TITLE
Sstop loading page after element is present.

### ISSUE THREAD

**Issue by uzhas-sovka** [lefthandedgoat/canopy#399]
How can I stop loading page after some element is present? In plain Selenium for c# it's possible to set page timeout to 1 sec, receive an error (page continues downloading) and then repeatedly check element presence in catch block.

It seems I can't do this in Canopy, `pageTimeout <- 1.0`
doesn't give me error.

I'd like something like

```fsharp
pageTimeout <- 1.0
try
  url "some url"
catch
  waitForElement ".number"
  pageTimeout <- 10
```

Thank you!

**Comment by lefthandedgoat** [comment]
Can you show me how to set the page timeout in C#?

`browser` is the IWebDriver and will have all of the same methods, so you should be able to do the same thing.

**Comment by uzhas-sovka** [comment]
Browser.Manage().Timeouts().PageLoad = new TimeSpan(0, 0, 0, 2);
try
 {
 Browser.Navigate().GoToUrl(WPDC.Url);
 }
 catch (Exception ex1)
{something to check presence }

**Comment by lefthandedgoat** [comment]
```
browser.Manage().Timeouts().PageLoad <- System.TimeSpan(0,0,0,2)
try url "http://www.something.com"
with ex -> displayed "selector"
```
That would be the same thing in canopy

**Comment by uzhas-sovka** [comment]
Thanks, it works.
BTW Canopy is amazing.

**Comment by lefthandedgoat** [comment]
Awesome!
