### ISSUE TITLE
[Question] Given no parallel testing, How might I use a canopy test runner function to run a group of tests, through multiple browsers one at a time?

### ISSUE THREAD

**Issue by jjmgitdot** [lefthandedgoat/canopy#401]
Sample code is below.  I can run a group of function tests on a specific browser but haven't figured out a way to: 

- run the tests through multiple browsers (chrome, firefox, ie, edge) maybe from a list?
- run the tests with multiple user types (utA, utB, utC, utD) with unique usernames and passwords
Any examples would be appreciated.

```fsharp
module TestRunner

open References (helpers)
open Commons (common functions)
open TopMenuNavTest
open MenuBarNavTest
open BrandsTest
open canopy

let TestBrowser = ChromeBrowser
start TestBrowser
let mainBrowser = browser
pin Right //FullScreen
resize (950, 1200)
url TestUrl

"input[name='UserName']" << UName
"input[name='Password']" << PWord
click "#SignInButton"

TopMenuNav
MenuBarNav
Brands

run()

printfn "press [enter] to exit"
System.Console.ReadLine() |> ignore

quit()
```

**Comment by lefthandedgoat** [comment]
Instead of using `run()` you can use `runFor` as described here: http://lefthandedgoat.github.io/canopy/testing.html

I haven't used it in a long time but it should work.

For the second part of your question, I will have to answer tomorrow when I have more time.  Hope the first part helps!

**Comment by lefthandedgoat** [comment]
For the second part of your question you can paramaterize your tests by wrapping them in functions like this

```
let loginWithUser username password = 
  sprintf "Logging with %s %s" username password &&& fun _ ->
    "input[name='UserName']" << username 
    "input[name='Password']" << password 
    click "#SignInButton"
```

Then you can register versions of the test like this:

```
[
  "user1", "password1"
  "user2", "password2"
  "user3", "password3"
]
|> List.iter (fun (username, password) -> loginWithUser username password)
```

Hope this helps.  Please let me know if you have any more questions, or these dont answer your current questions perfectly.

**Comment by jjmgitdot** [comment]
1.) I couldn't get 'runFor' to work... (I am running VS 2017 Pro on Windows 10 and .NETframework 4.6.2)

2.) I also have some browser issues:
- Edge
The canopy 'browserstartmode' for edge only is available as EdgeBETA.  I think this is causing a problem with selectors like 'click' where I get a Canopy exception timeout trying to find the login click:	
click "#SignInButton"
Inspecting the element shows: <button name="SignInButton" class="button blue" id="SignInButton" type="submit">Sign In</button>
I can get by the 'signinbutton' issue with 'press tab', 'press enter' but this is problematic...
I then got a timeout at on another element:     click "a[href='/Home/Help']"

- Adjusting the size of the browser view
Is there a place to change the browser views for each type in canopy or in the Selenium WebDriver?

Example... IE 11 - I set my default view to 50% to try to compensate for the webdriver browser view launched at 100%. (VS open on left and browser pinned to right.)  I get an exception:
OpenQA.Selenium.WebDriverException occurred
  HResult=0x80131500
  **Message=Unexpected error launching Internet Explorer. Browser zoom level was set to 50%. It should be set to 100%**
  Source=WebDriver
  StackTrace:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(InternetExplorerDriverService service, InternetExplorerOptions options)
   at OpenQA.Selenium.IE.InternetExplorerDriver..ctor(InternetExplorerDriverService service)
   at canopy.core.start(BrowserStartMode b)

3.) Thanks for the example of parameterizing the login.  I think that code could be moved to my "Commons" module, but where/how do you register the versions of the test?  In the TestRunner module? 
Thanks.

**Comment by lefthandedgoat** [comment]
@jjmgitdot I am working through getting a VM setup to work through this for you.

**Comment by lefthandedgoat** [comment]
1) I was wrong, you need to put `runFor [chrome; firefox]` before `run()` and remove any manual `start browser` you have.

**Comment by lefthandedgoat** [comment]
Ive spent like 8 hours patching this VM and it still isn't done.  Hopefully tomorrow I can have latest Edge and try to repro your problems.

**Comment by jjmgitdot** [comment]
I got the runFor working.  Still have issues with Edge.  Selenium points to the microsoft web driver site https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/#downloads  and I have the latest installed, so I think the issue maybe in the edgeBETA [BrowserStartMode (canopy.core.edgeBETA)] not pointing to the correct driver?  Sorry for the problems you have had getting your VM setup.

**Comment by lefthandedgoat** [comment]
I have it mostly setup.  It runs but a few tests in my basic regressions suite fail (but work on FF and Chrome).  I now remember why I called it EdgeBETA.  Its because my opinion at the time was that Edge's support of Selenium was Beta level.

You can see here that its not really doing anything special, just calling Edge from Selenium.  https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.fs#L854

For your click Sign in Issue, is the page public so I can test it also?  Clicking something by ID should work without a problem.

For your resize question, there are a few ways to do it.  You can use the `pin` function to set something to the left half, right half, or full screen.  You can also use `resize` to change the dimensions of the browser.  See here: http://lefthandedgoat.github.io/canopy/actions.html

For structuring your code, I do it like show in this example project:

https://github.com/lefthandedgoat/canopyStarterKit

**Comment by jjmgitdot** [comment]
No the sign-in is for a b2b site.  Updated all NuGet pkgs: canopy, FSharp.Core, FSharp.Data, Selenium.WebDriver, and Selenium.Support and Edge seems to be working better with selectors and ids.

Thanks for structuring example.

Last issue is IE - terribly slow to load and navigation sleep 5-7 in some places or adding waits that are way different than other browsers.  I may have to create separate modules for testing it.

**Comment by lefthandedgoat** [comment]
Yes I personally just test with chrome and sometimes firefox.  Never IE/Edge.  I have never worked at a place where providing coverage across all browsers was reasonable, because in general I couldn't get people to fix bugs =(.
