### ISSUE TITLE
How to run setup Safari to run Canopy tests on Windows 10?

### ISSUE THREAD

**Issue by adalenthya** [lefthandedgoat/canopy#408]
Has anyone been able to run Canopy tests on Safari web browser, on Windows? If yes, please tell me how did you manage to get the driver installed?

This is what I found: https://lavanyaaraga.wordpress.com/2013/11/05/how-to-configure-selenium-webdriver-in-windows-safari-browser/ but I can't create a certificate (step.4) because apple tells me to enroll in the apple developer program, for which I have to pay a monthly fee. 

Any ideas, would be greatly appreciated.

**Comment by lefthandedgoat** [comment]
Safari for Windows is not a thing anymore.  I believe they stopped working on it at version 5.  Current version of Safari is 11 on OSX.  Sorry.

**Comment by adalenthya** [comment]
Thank you, I was almost sure that would be the answer.
