### ISSUE TITLE
Packages are not getting restored with latest code.

### ISSUE THREAD

**Issue by devanshudravid** [lefthandedgoat/canopy#419]
My colleague took the latest code and the packages not getting downloaded at his machine.

I have the package date 27 Feb 2018 and its working.

I saw some new changes happened in build.cmd. Maybe those are affecting it.

**Comment by lefthandedgoat** [comment]
For the canopy source?

**Comment by lefthandedgoat** [comment]
I was able to reproduce it on a machine w/o canopy.  Will look into it, thanks!

**Comment by lefthandedgoat** [comment]
Please try again, I accidentally checked in a file I shouldn't.  Thanks for reporting!

**Comment by devanshudravid** [comment]
Yup!! working fine!

Thank you :)
