### ISSUE TITLE
.Net Standard 2.0 Core Support?

### ISSUE THREAD

**Issue by richardjharding** [lefthandedgoat/canopy#420]
Is there work underway to support dotnet core?

**Comment by lefthandedgoat** [comment]
Yes on this branch: https://github.com/lefthandedgoat/canopy/tree/AddSupportForParallelWithHaf

**Comment by lefthandedgoat** [comment]
I've completed canopy 2.0 which has both .net standard 2.0 support and parallel support.

You can download it here: https://www.nuget.org/packages/canopy/2.0.0

You can read the upgrade documentation here: http://lefthandedgoat.github.io/canopy/upgrade1to2.html
