### ISSUE TITLE
Find id without exact id

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#421]
Is there a way to find an id if you only know the id ends with certain text?

**Comment by lefthandedgoat** [comment]
Yes!

`#some_id` is shorthand for `[id='some_id']`

There are all kinds of fuzzy matching you can do on css selectors.  See the full list here:

https://oscarotero.com/jquery/

For your example you want to do something like `"[id $= 'field1']"`

You can use that selector on this page and see that it returns the field with id `testfield1`

http://lefthandedgoat.github.io/canopy/testpages/

Hope this helps!

**Comment by rodsantest1** [comment]
Thank you!

**Comment by amirrajan** [comment]
@rodsantest1 generally speaking: if there is a css selector for it, then it can be done. So I tend to google: "css selector id ends with" and use that stringing within Canopy to see if it works.
