### ISSUE TITLE
How can I assert checkbox is checked?

### ISSUE THREAD

**Issue by rodsantest1** [lefthandedgoat/canopy#425]
Hi all, I'm trying to verify that my checkbox is checked. The checkboxes are from bootstrap's glyphicons. There doesn't seem much to go on for me to assert. 

I was able to check it like this:
`click (nth 0 "[class*='glyphicon']")`

But I can't seem to assert it. Any ideas? I was thinking going by class contains glyphicon-check?

```
<td class="text-center update-status">
    <span id="MainContent_GridView1_Label2_0" class="glyphicon glyphicon-check"></span>
    <input type="hidden" name="ctl00$MainContent$GridView1$ctl02$hdnTaskId" id="hdnTaskId" value="1">
</td>
```

**Comment by lefthandedgoat** [comment]
`checked "#hdnTaskId"` should work
You can also change your initial code to 
`click ".glyphicon-check:first"`

**Comment by rodsantest1** [comment]
The span is actually the checkbox. The hidden field is a record id that I use for something else. But I thought I would include the whole picture.

**Comment by lefthandedgoat** [comment]
spans can't be checked, once you click the span, does the markup change?

**Comment by lefthandedgoat** [comment]
I would put an arbitrary class in there to make it unique, like an id, and do this (may require adjusting to work)

```
let customChecked selector = waitFor (sprintf "%s not checked" selector) (fun _ -> 
  let e = element selector
  e.GetAttribute("class").Contains("glyphicon-check")
)

click ".new-class"
customChecked ".new-class"
```

**Comment by rodsantest1** [comment]
I liked,
`click "glyphicon-unchecked:first`
I'm just going to do
`click "glyphicon-check:first" `
to assert that it took.

Thanks so much for your help.
