### ISSUE TITLE
How works scripting with parallel testing?

### ISSUE THREAD

**Issue by kikkoi** [lefthandedgoat/canopy#430]
I am interested to canopy 2.0. Can use surely the with parallel testing F# Interactive? Can give simple example of parallel testing with F# Interactive?

**Comment by lefthandedgoat** [comment]
I do not have any examples using the parallel testing in interactive.

You should be able to, but only if you are able to run unit tests in parallel in interactive.  canopy 1.x used a global mutable instance of a browser which inhibited having multiple browsers and tests going at the same time.  Two new apis are introduced in 2.0 which fix this.  Running tests in parallel has not been added to the runner, you will need to use a test runner like Expecto or nUnit for that.

**Comment by lefthandedgoat** [comment]
I will look into this tonight.  I never use interactive with testing, so I am very rusty.

**Comment by haf** [comment]
@kikkoi You can use https://github.com/haf/canopy/blob/parallel/tests/ParallelUsage/Explore.fsx as an example, if you want an fsx example that works. I haven't released a separate nuget with these changes yet though.
