### ISSUE TITLE
How can I automate clicking these elements?

### ISSUE THREAD

**Issue by kevinmcfarlane** [lefthandedgoat/canopy#435]
[JobServe job search](https://www.jobserve.com/gb/en/JobListing.aspx?shid=DA00DD8CD8985D54FC&js=1)

If you look at the dropdowns for "Summary View" or "20 Jobs Per Page" or "Best Match." If you mouse over then the dropdowns become available and you can select something. I tried writing `hover "Best Match" `hoping I could then click on an element. But that does nothing.

Any ideas?

**Comment by lefthandedgoat** [comment]
```
hover "#viewSelect"
click "#lkPreview"
```
This worked for me.  This site does not use standard Select/option tags so it makes it more challenging.

**Comment by lefthandedgoat** [comment]
Is the delay in the rendering of the drop down?

Its not really something that I can control, they wrote their site in a really strange way.

**Comment by kevinmcfarlane** [comment]
> Is the delay in the rendering of the drop down?

Yes. No worries. I think the JobServe site could do with a revamp to be honest. But for a job seeker they do seem to offer the best in terms of _overall_ features, despite frustrations!

Anyway, I'm just experimenting with Canopy right now.
