### ISSUE TITLE
Gitter channel

### ISSUE THREAD

**Issue by nojaf** [lefthandedgoat/canopy#443]
It be nice if we could ask little howto questions on gitter.

**Comment by amirrajan** [comment]
GH issues are more searchable (imho). I don't think there'd be enough people on gitter to constitute a dedicated room. What are your thoughts about having a channel in the F# slack??

**Comment by lefthandedgoat** [comment]
I have a strong preference for GH issues.  I don't even keep slack open anymore.  Please feel free to ask even the most boring questions here.  It doesn't bother me and I know that other people will read them from time to time and it will help them also.

**Comment by nojaf** [comment]
Ok, thanks for your input. I'll post questions on GH however small 😄
