### ISSUE TITLE
Highlight function broken in canopy classic

### ISSUE THREAD

**Issue by warn4n** [lefthandedgoat/canopy#447]
The highlight function is broken in canopy.classic. You forgot to pass the browser. It might be a good practice to put type annotations on public APIs to catch this kind of thing.

**Comment by lefthandedgoat** [comment]
Good find,  thanks for the heads up!

**Comment by lefthandedgoat** [comment]
This should be fixed here:

https://www.nuget.org/packages/canopy/2.1.0
