### ISSUE TITLE
Fake user geolocation

### ISSUE THREAD

**Issue by nojaf** [lefthandedgoat/canopy#448]
Hi, is it possible to simulate the user's location somehow?
I saw [this](https://stackoverflow.com/questions/8411816/how-do-i-enable-geolocation-support-in-chromedriver-for-selenium) but you like quite the hack. A solution that work in chrome would suffice.

**Comment by lefthandedgoat** [comment]
I have never tried.  Reading that ticket, if chrome won't let you set a flag to fake it, you will have to use JS to fake it like they suggest.  Or you could have the developers who work on the site you are testing provide a js method to call to set it for you, or maybe hardcode geolocation for a specific test user etc.

Lots of hacky ways, but it doesn't look like there is a 'clean' way.

**Comment by nojaf** [comment]
Ok, thanks for your comment.
