### ISSUE TITLE
Parallelization ignores configuration/reporter

### ISSUE THREAD

**Issue by curdincaspar** [lefthandedgoat/canopy#450]
I'm currently migrating my own parallelization with AppDomains to the new parallelization canopy offers.
I'm using the instance based tests and have some configuration like failureScreenshotsEnabled = true and the TeamCityReporter. This is all ignored.

Is this a bug/not yet implemented or is this because of the classic runner which does not support the parallel tests? In that case I have to build all this functionality in the tests by myself? Not a problem just need to know it :)

**Comment by lefthandedgoat** [comment]
The Html reporter is friendly to parallel but the runner is not.

The runner controls things like screenshot on failure and sending messages to the HTML report.

You are probably using a different runner to get parallel support like nUnit, or expecto.

I have a parallel runner but it doesn't have all the nice stuff that canopy has, but is API compatible with the canopy runner.

One day I may get it integrated, but I don't have the mental energy to do it right now =(

**Comment by lefthandedgoat** [comment]
Link to parallel runner: https://github.com/lefthandedgoat/prunner

**Comment by curdincaspar** [comment]
I'm already using xUnit to execute the tests.
So I'll do the screenshot logic on failure by myself.

Thank you for the parallelization and hope you feel better soon :)
