### ISSUE TITLE
Use multiple reporters?

### ISSUE THREAD

**Issue by Pwntheon** [lefthandedgoat/canopy#459]
Hi.

We would like to use both the junit reporter (for info in jenkins) and the livehtmlreporter (for screenshots and a better overview when debugging.

Is it possible to add several reporters easily? I'm not very fluent in F# so apologies if this is trivial.

**Comment by lefthandedgoat** [comment]
For this you would have to make your own reporter (implement IReporter) and inside of it have 1 instance of jUnit reporter and 1 instance of livehtmlreporter and for each calls just make the same call for both of your other reporters.

Just a wrapper.

You can see how reporters are done here:

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/reporters.fs

**Comment by Pwntheon** [comment]
That was my assumption. I was hoping for something easier, but i guess that'll do.

Thanks for the quick reply.
