### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by IvanRainbolt** [lefthandedgoat/canopy#461]
![image](https://user-images.githubusercontent.com/7623933/48917304-1910e000-ee54-11e8-9eca-58ca717edee9.png)

**Comment by lefthandedgoat** [comment]
Yes I need to remove that.  Its just auto generated docs from reflection.

**Comment by chrisatx** [comment]
Voting to fix the API generation rather than abandon. 
I like to be able to search entire API on a single page. 
I will try to circle back and see if I can pitch in a suggested fix, but I don't have experience with the auto generated API process.

**Comment by JeremyBellows** [comment]
Fixed in #491 

https://lefthandedgoat.github.io/canopy//Api_Reference/canopy/canopy.html
