### ISSUE TITLE
`build.cmd RunTests` on Windows throws error

### ISSUE THREAD

**Issue by manishdube** [lefthandedgoat/canopy#464]
for the Site solution `build.cmd RunTests` on Windows throws error
The request was aborted: Could not create SSL/TLS secure channel. (Github)

error log 
_________________________________________________
No version specified. Downloading latest stable.
The request was aborted: Could not create SSL/TLS secure channel. (Github)
Paket version 5.189.1
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 672 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target RunTests:
<== RunTests
   <== CopyAssets
      <== CopyBinaries
         <== Build
            <== AssemblyInfo
               <== Clean

The resulting target order is:
 - Clean
 - AssemblyInfo
 - Build
 - CopyBinaries
 - CopyAssets
 - RunTests
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/30/2018 4:16:12 AM.
Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master
\Site.sln" on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master
\Site.sln" (1) is building "C:\Users\Admin\Downloads\turtletestAutomation-master\turtlete
stAutomation-master\src\tests\tests.fsproj" (2) on node 1 (Rebuild target(s)).
C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\test
s\tests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAut
omation-master\src\tests\tests.fsproj" (Rebuild target(s)) -- FAILED.

Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAut
omation-master\Site.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sl
n" (Rebuild target) (1) ->
"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tes
ts\tests.fsproj" (Rebuild target) (2) ->
  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\te
sts\tests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:03.29
Running build failed.
Error:
Building C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0028455
AssemblyInfo   00:00:00.0458439
Total:         00:00:11.6638233
Status:        Failure
---------------------------------------------------------------------
  1) Building C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln failed with exitcode 1.
  2) MSB4057: C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\tests.fsproj(0,0): The target "Rebuild" does not exist in the project.
---------------------------------------------------------------------

_________________________________________________

**Comment by lefthandedgoat** [comment]
I updated latest paket and pushed it, please try again

**Comment by manishdube** [comment]
Still fails at a later stage... says 'The target "Rebuild" does not exist in the project.'

______________________________________________________________________________________

Checking Paket version (downloading latest stable)...
Paket.exe 5.193.0 is up to date.
Paket version 5.193.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 587 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target RunTests:
<== RunTests
   <== CopyAssets
      <== CopyBinaries
         <== Build
            <== AssemblyInfo
               <== Clean

The resulting target order is:
 - Clean
 - AssemblyInfo
 - Build
 - CopyBinaries
 - CopyAssets
 - RunTests
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/30/2018 5:15:40 AM.
Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln"
 on node 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln"
 (1) is building "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\
src\tests\tests.fsproj" (2) on node 1 (Rebuild target(s)).
C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\tests.fs
proj : error MSB4057: The target "Rebuild" does not exist in the project.
Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-ma
ster\src\tests\tests.fsproj" (Rebuild target(s)) -- FAILED.

Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-ma
ster\Site.sln" (Rebuild target(s)) -- FAILED.


Build FAILED.

"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln" (Rebuil
d target) (1) ->
"C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\tests.f
sproj" (Rebuild target) (2) ->
  C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\tests.
fsproj : error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:05.47
Running build failed.
Error:
Building C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0020426
AssemblyInfo   00:00:00.0294545
Total:         00:00:06.5506061
Status:        Failure
---------------------------------------------------------------------
  1) Building C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\Site.sln failed with exitcode 1.
  2) MSB4057: C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master\src\tests\tests.fsproj(0,0): The target "Rebuild" does not exist in the project.
---------------------------------------------------------------------

C:\Users\Admin\Downloads\turtletestAutomation-master\turtletestAutomation-master>


_______________________________________________________________________________________

**Comment by lefthandedgoat** [comment]
Ive updated to .net 4.6.2 which may help you.

If it does not I need to know what version of windows you are on plus what version of Visual Studio

**Comment by manishdube** [comment]
Hello,
Below are the answers to you question.
1. 
C:\WINDOWS\system32>ver
Microsoft Windows [Version 10.0.17134.407]
2. 
when i try to update the .NET Framework i get the below prompt.

".NET Framework 4.6.2 or a later update is already installed on this computer."
3. 
regedit and navigating to below shows i have .NET Framework 4.7.03056 installed.

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\1033

**Comment by lefthandedgoat** [comment]
Do you still have the issue?  You can open the project in VS and right click on the Tests project, go to properties and change it to 4.7.x if you want.

**Comment by lefthandedgoat** [comment]
With latest from the repo that is

**Comment by manishdube** [comment]
no change ... :(

-------------------------
Checking Paket version (downloading latest stable)...
Paket.exe 5.193.0 is up to date.
Paket version 5.193.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 297 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target RunTests:
<== RunTests
   <== CopyAssets
      <== CopyBinaries
         <== Build
            <== AssemblyInfo
               <== Clean

The resulting target order is:
 - Clean
 - AssemblyInfo
 - Build
 - CopyBinaries
 - CopyAssets
 - RunTests
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/30/2018 12:05:48 PM.
Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" on nod
e 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" (1) is
 building "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\test
s.fsproj" (2) on node 1 (Rebuild target(s)).
C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj :
error MSB4057: The target "Rebuild" does not exist in the project.
Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\sr
c\tests\tests.fsproj" (Rebuild target(s)) -- FAILED.

Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Si
te.sln" (Rebuild target(s)) -- FAILED.


Build FAILED.

"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" (Rebuild targe
t) (1) ->
"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj"
(Rebuild target) (2) ->
  C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj
: error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.81
Running build failed.
Error:
Building C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0020369
AssemblyInfo   00:00:00.1836389
Total:         00:00:03.1879124
Status:        Failure
---------------------------------------------------------------------
  1) Building C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln failed with exitcode 1.
  2) MSB4057: C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj(0,0): The target "Rebuild" does not exist in the project.
---------------------------------------------------------------------
-------------------------

**Comment by manishdube** [comment]
I think i see the issue. The visual studio does not have the 4.7.x .NET Framework in its drop down list.
It only goes up to 4.6.1

**Comment by manishdube** [comment]
So the real question is how would i get visual studio to show the installed .NET Framework 4.7.x under that list. :)

**Comment by lefthandedgoat** [comment]
okay set it 4.6.1 and try that.

It was working for me on 4.5.2 so I dont think 4.7.x is the actual problem.

See what version of VS you have, I am on 15.7.5

**Comment by manishdube** [comment]
im feeling stupid now .... :( I double checked all. My cmd folder, my 
On Visual Studio 15.9.1
Changed to .NET 4.5.2 --> saved project --> from the cmd prompt ran <build.cmd RunTests>

see the error below.

Changed to .NET 4.6.1 --> saved project --> from the cmd prompt ran <build.cmd RunTests>
see the same below error.


____________________________
Checking Paket version (downloading latest stable)...
Paket.exe 5.193.0 is up to date.
Paket version 5.193.0
The last restore is still up to date. Nothing left to do.
Performance:
 - Runtime: 335 milliseconds
Building project with version: LocalBuild
Shortened DependencyGraph for Target RunTests:
<== RunTests
   <== CopyAssets
      <== CopyBinaries
         <== Build
            <== AssemblyInfo
               <== Clean

The resulting target order is:
 - Clean
 - AssemblyInfo
 - Build
 - CopyBinaries
 - CopyAssets
 - RunTests
Starting Target: Clean
Deleting contents of bin
Deleting contents of temp
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\AssemblyInfo.fs".
Finished Target: AssemblyInfo
Starting Target: Build (==> AssemblyInfo)
Building project: C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln
  c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
c:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe  "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\packages\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 4.7.3056.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 11/30/2018 12:32:45 PM.
Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" on nod
e 1 (Rebuild target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Release|Any CPU".
Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" (1) is
 building "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\test
s.fsproj" (2) on node 1 (Rebuild target(s)).
C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj :
error MSB4057: The target "Rebuild" does not exist in the project.
Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\sr
c\tests\tests.fsproj" (Rebuild target(s)) -- FAILED.

Done Building Project "C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Si
te.sln" (Rebuild target(s)) -- FAILED.


Build FAILED.

"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln" (Rebuild targe
t) (1) ->
"C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj"
(Rebuild target) (2) ->
  C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj
: error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.23
Running build failed.
Error:
Building C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln failed with exitcode 1.

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0034228
AssemblyInfo   00:00:00.0218707
Total:         00:00:02.5848739
Status:        Failure
---------------------------------------------------------------------
  1) Building C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\Site.sln failed with exitcode 1.
  2) MSB4057: C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master\src\tests\tests.fsproj(0,0): The target "Rebuild" does not exist in the project.
---------------------------------------------------------------------

C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master>
C:\Users\Admin\Downloads\turtletestAutomation-master (1)\turtletestAutomation-master>
____________________________

**Comment by lefthandedgoat** [comment]
I see in your messages that its using MSBuild v4 and for me its v15

Can you see if you have any of the three folders here in green?

https://github.com/fsharp/FAKE/commit/b2e29f30b7c638964cd4d81d2761871ce9f016c8

I have also checked in one more change which may help, try getting latest.

**Comment by manishdube** [comment]
WORKS !!! thanks @lefthandedgoat  !!!
