### ISSUE TITLE
How to capture the text from popup messages.

### ISSUE THREAD

**Issue by RutujaNagare** [lefthandedgoat/canopy#467]
Hi,

I want read a text from popup message which get vanished after few seconds from screen.
I am able to get the x-path for the message but while trying to read the text not able to read the same.

Could you please suggest how should i proceed?

Sample code I am using
let temp = //div[@class='toast-message']
read temp

**Comment by lefthandedgoat** [comment]
```
displayed temp
let value = read temp
```

**Comment by RutujaNagare** [comment]
It wokrs..Thank you...
