### ISSUE TITLE
save screenshot as png

### ISSUE THREAD

**Issue by hroe** [lefthandedgoat/canopy#470]
Hi,
screenshots are currently saved as jpg.
Is it possible to save them as png?
Perhaps by adding a third parameter that gives the file format, such as png, jpg etc
Thanks, Herman

**Comment by lefthandedgoat** [comment]
There are three ways to do this,

Via configuration/param like you suggested.

You can make your own screenshot method that behaves the way you like, using the existing code as a guide: https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.parallell.functions.fs#L74

Convert all jpg to png after they are created, using this code as a guide:
http://james-ramsden.com/c-convert-all-images-in-a-folder-from-png-to-jpg/

If #2 or #3 are easy enough for you, that would be my preference.  If not, I can add configuration to keep things backwards compat but provide the functionality you want.

**Comment by hroe** [comment]
Thanks for explaining, I will try #2, Herman
