### ISSUE TITLE
How to execute canopy Automation scripts of web application to mobile browser platform?

### ISSUE THREAD

**Issue by Suvarnaraut** [lefthandedgoat/canopy#471]
Hi,

I want to execute my canopy automation script on different mobile browser platforms, how to do that? what all driver files i will be needed and what setup i have to do for that?
Please guide.

Thanks,

**Comment by lefthandedgoat** [comment]
For firefox: https://github.com/mozilla/geckodriver/releases
For edge: https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by lefthandedgoat** [comment]
https://github.com/fsprojects/Canopy.Mobile

I do not support this package, I only helped get it started.  Mobile testing is a completely different beast.
