### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by olivercoad** [lefthandedgoat/canopy#472]
In the docs **[getting started](https://lefthandedgoat.github.io/canopy/)** there is a typo in step **4**:

```fsharp
canopy.configruation.chromeDir <- AppContext.BaseDirectory
```

should be 

```fsharp
canopy.configuration.chromeDir <- System.AppContext.BaseDirectory
```

Would just make a pull request but that line doesn't exist in the `index.fsx` file 🤨.
https://github.com/lefthandedgoat/canopy/blob/e8d81c81dd5d279459d574c5e9e8c41180089c7e/docs/content/index.fsx#L48-L53

**Comment by lefthandedgoat** [comment]
Thanks.  I've fixed this.

It doesnt exists in the fsx file because thats the source that generates the documentation (that lives on gh-pages branch).  After updating to .net core the tooling that I used to documents wasnt working, or I was too lazy or something. Thanks again for letting me know!

**Comment by olivercoad** [comment]
Ok, are you just updating the html files manually in the gh-pages branch at the moment then? Is there anything that can be done to help fix that?

`configruation` is still spelled wrong, should be `configuration`.

**Comment by lefthandedgoat** [comment]
Correct.  

In terms of fixing, I probably just need to update everything I used.  canopy is like 8 years old and the build scripts are probably 6 and haven't been updated cause they always 'just worked'.  Then with .net core I think they stopped but I spent 40 hours on that so fixing documentation scripts wasnt high on the list of things to do =\

**Comment by olivercoad** [comment]
Thanks.
Had no idea canopy was that old. Tried it for the first time last night and it's brilliant!

**Comment by lefthandedgoat** [comment]
Awesome, please open a ticket if you have any questions and I will be happy to help!  Thanks for bringing up these issues!
