### ISSUE TITLE
HTML Reporter does not pass the case even if condition is true

### ISSUE THREAD

**Issue by RutujaNagare** [lefthandedgoat/canopy#475]
Hi,

I Tried below code to verify the expected value and actual value are equal, even though my values are matching canopy is failing my condition.

Could you please check and suggest a solution?

![Canopy_Error](https://user-images.githubusercontent.com/46703382/62608595-b7c76900-b91d-11e9-8f51-64eb9735e2fe.png)

**Comment by lefthandedgoat** [comment]
You are using `==` which takes a selector and makes sure that it has the right values.

In your code, you are reading the value and trimming it, and then treating that as a selector.

You will want to use `===` instead which does not think its receiving a selector and then doing the comparison, it just does a simple comparison.

Read more here: http://lefthandedgoat.github.io/canopy/assertions.html

**Comment by RutujaNagare** [comment]
I tried with '===' operation  and this solution works for me.
Thank you so much.
