### ISSUE TITLE
How do I click link in table header?

### ISSUE THREAD

**Issue by kevinmcfarlane** [lefthandedgoat/canopy#479]
Looks like this. So I want to click the "#"
```
<table id="processTable" class="table admin-table table-striped table-bordered">

<th>    <a href="#">
        <i class="glyphicon glyphicon-sort" data-sort-name="ActivityType"></i>
    </a>
Activity Type</th>
```

**Comment by lefthandedgoat** [comment]
`click "#processTable a"`

**Comment by kevinmcfarlane** [comment]
Thanks for the speedy response Chris. In my case I actually needed to click the 4th header cell so I used

`click "#processTable th:nth-child(4) a"`

and it works fine. :)
