### ISSUE TITLE
All links and resources on the website refer to c:\projects\canopy\...

### ISSUE THREAD

**Issue by Pwntheon** [lefthandedgoat/canopy#484]
Title should be enough. Check the links on http://lefthandedgoat.github.io/canopy/

**Comment by lefthandedgoat** [comment]
Yes I broke this yesterday and I am working on it, thanks.

**Comment by OmanF** [comment]
Anything we can do to help?

BTW, for those who need the docs, while it's harder to "parse by humans" than a nicely presented web page, the docs are under the `docs` folder in the repo's root, so it _is_ accessible if you need it.

**Comment by lefthandedgoat** [comment]
@OmanF I just have to roll my sleeves up and do it.  I will work on it tonight.

**Comment by lefthandedgoat** [comment]
Asking for help from jeremy in other thread https://github.com/lefthandedgoat/canopy/pull/474

**Comment by olivercoad** [comment]
> the docs are under the `docs` folder in the repo's root, so it _is_ accessible if you need it.

or on Wayback Machine https://web.archive.org/web/20190526141241/http://lefthandedgoat.github.io/canopy/

**Comment by lefthandedgoat** [comment]
I've re-pushed the previous version of the docs.  Jeremy is still working on getting everything updated.

**Comment by JeremyBellows** [comment]
Fixed in #491
