### ISSUE TITLE
WIP in XUnit.

### ISSUE THREAD

**Issue by felipeotarola** [lefthandedgoat/canopy#496]
Hi.
I read a comment from lefthandedgoat in this [thread] (https://github.com/lefthandedgoat/canopy/issues/58) that WIP cannot be used with xUnit. 
Now the comment was from 2012 and my question is.
- Has this been changed? Any one that have make it work?

I have been looking in multiple places and tested different ways but with no luck :)

Thanks in advance,

**Comment by lefthandedgoat** [comment]
WIP is a test mode that is implemented and controlled by the canopy test runner.  xUnit is its own test runner.  Its a simple flag that gets turned on/off in a WIP test in canopy, so you could do that yourself in your test.

`canopy.configuration.wipTest <- true` at the start of your test, and set to false at the end.

This will slow your test down and attempt to put color markers around html elements that its about to interact with.

marking a test as WIP will only run it and other tests marked as WIP and skip all of the non-wip tests.  You can achieve this by just running the tests you want in your test runner gui.

Hope this helps!

**Comment by felipeotarola** [comment]
This worked for me! Thank you for the  help and the explanation
