### ISSUE TITLE
Expose ChromeOptions

### ISSUE THREAD

**Issue by fischgeek** [lefthandedgoat/canopy#507]
**Is your feature request related to a problem? Please describe.**
I've found myself in a position where I need to set some chrome options before execution. Specifically the "Download PDF files instead of automatically opening them in Chrome" option. 

**Describe the solution you'd like**
It would be really nice if this could be configurable prior to running the test.

**Describe alternatives you've considered**
Right now, I navigate to the screen for the test by doing `url chrome://settings/content/pdfDocuments?search=pdf` and then prompting to turn it on before continuing. While this works okay, it's not fully automated.

**Additional context**
If Selenium exposes more ChromeOptions I would like to see those available as well to optimize specific tests in the future. Mostly just focused on the pdf download option now.

**Comment by lefthandedgoat** [comment]
You can start a ChromeWithOptions to pass ChromeOption in.

https://github.com/lefthandedgoat/canopy/blob/master/src/canopy/canopy.parallell.functions.fs#L850

**Comment by fischgeek** [comment]
Sweet! I'm not quite up to speed on how to fully use Canopy outside of starter kit and demos I've read so not sure how to implement this. Not to mention what the specific chrome option is; I'll of course have to research that up a bit. Thank you!

**Comment by lefthandedgoat** [comment]
@fischgeek No problem! Dont forget the documentation, http://lefthandedgoat.github.io/canopy/

**Comment by fischgeek** [comment]
Haha! yes, thank you. The documentation page has been a bookmark bar button for the past week. I'm just trying to comb through it to find out how to set this up.

**Comment by fischgeek** [comment]
Found it! Thanks again!

[This SO article](https://stackoverflow.com/a/58598697/3242752) helped as well.

```
let startMode = 
            let options = Chrome.ChromeOptions()
            //options.AddArgument("download.open_pdf_in_system_reader")
            //options.AddArgument("plugins.always_open_pdf_externally")
            //options.AddUserProfilePreference("plugins.always_open_pdf_externally", "false")
            options.AddUserProfilePreference("download.prompt_for_download", false)
            options.AddUserProfilePreference("plugins.plugins_disabled", "Chrome PDF Viewer")
            options.AddUserProfilePreference("plugins.always_open_pdf_externally", true)
            let start = canopy.types.BrowserStartMode.ChromeWithOptions options
            start
        
start startMode
```
