### ISSUE TITLE
'count' finds exactly 1 matching checkbox, but subsequent 'check' times out.

### ISSUE THREAD

**Issue by toddmarek** [lefthandedgoat/canopy#508]
Hi, 

Thanks to all the canopy developers. It is very elegant and I'm loving it already.

**Describe the bug**
I am running some tests that require checkboxes to be checked.

When I run 'count' using the element ID as the selector, it finds exactly 1 matching checkbox, but subsequently try to 'check' the checkbox returns a times out error:
`canopy.types.CanopyWaitForException: 'Condition not met in given amount of time. If you want to increase the time, put compareTimeout <- 10.0 anywhere before a test to increase the timeout`

I have added `compareTimeout <- 10.0` right below the test (see below), and it makes not difference.

**To Reproduce**
Here is the test code:

open canopy.runner.classic
open canopy.configuration
open canopy.classic

canopy.configuration.chromeDir <- System.AppContext.BaseDirectory

//start an instance of chrome
start chrome

let baseUrl = "https://ascent.greencountywi.org/LandRecordsStaging/"

"asserting there is exactly 1 'remember me' checkbox" &&& fun _ ->
    url baseUrl 

    click "#loginLink"

    count "#RememberMeChkBox" 1

"checking the 'remember me' checkbox" &&& fun _ ->
    compareTimeout <- 10.0
    check "#RememberMeChkBox"

**Expected behavior**
I expected the #RememberMeChkBox to be checked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 86.0.4240.111 (Official Build) (64-bit)

Any insight is appreciated! 

Thanks again!

**Comment by JeremyDuMonde** [comment]
Could you share the snippet of html with the checkbox?

**Comment by toddmarek** [comment]
Hi Jeremy,

Thanks so much for the speedy reply and the helpful information! That did in fact address the issue. Apologies for taking up your time. 

Your help is really appreciated!

Best,
Todd

**Comment by JeremyDuMonde** [comment]
You're welcome! :)

Let us know if you have any other questions

Here's the code snippet for the function for the interested
https://github.com/lefthandedgoat/canopy/blob/c13b4666eedd16d8e1a1ed57dfa24d21a93285f6/src/canopy/canopy.parallell.functions.fs#L726-L737
