### ISSUE TITLE
HTML Live Reporter template 404's due to change to github.io domain.

### ISSUE THREAD

**Issue by avargaslopez** [lefthandedgoat/canopy#516]
**Describe the bug**
After April 15th GitHub pages "github.com" is now deprecated in favor of "github.io". 

This breaks live html reporting unless you redirect to .io

**Comment by lefthandedgoat** [comment]
@avargaslopez this thread shows how to work around it for now. https://github.com/lefthandedgoat/canopy/issues/515

**Comment by ariesdumonde** [comment]
Fixed in commit 4688c4a06621f12fdb34a17839001dbbbc0758a3
