### ISSUE TITLE
Canopy HTML Log file is all "grey", no color coding, doesn't show number of Passes & Fails

### ISSUE THREAD

**Issue by dvaston** [lefthandedgoat/canopy#518]
**Describe the bug**
Note: This issue is related to https://github.com/lefthandedgoat/canopy/issues/516 and https://github.com/lefthandedgoat/canopy/issues/515, but I wasn't sure if this was a separate issue and if there might be a quick fix for it.

I have upgraded our F# project to use the latest version of Canopy 2.1.5 and I have followed the workaround described in the tickets above, to manually force our project to point to the new "reporttemplate.html" file

...
let initialLiveHtmlReporter = new LiveHtmlReporter(Chrome, currentRunPath)
initialLiveHtmlReporter.reportTemplateUrl <- "https://lefthandedgoat.github.io/canopy/reporttemplate.html"
reporter <- initialLiveHtmlReporter :> IReporter
...

However, after I have run a test for our project, the HTML log file for the test run all looks "grey", and doesn't have any "color coding" and also you can't see the total number of Passes or Failures.

Normally if a Canopy Test is "passed" that section should be green, and for a fail it should be red/pink.

Refer to screenshot attached below (note: I have blacked out all the sensitive information).

Am I using the correct HTML template file? Or should I be pointing at something else?

Also note: is there a copy of the old file "reporttemplatep.html" somewhere around for reference? Possibly I can host this file through Internet Information Service (IIS) on our internal network as a workaround?

Thanks in advance.

![Canopy_HTML_Log_Issue](https://user-images.githubusercontent.com/16095311/117741700-63fe5800-b246-11eb-9d9a-6a51290a75fd.png)

**Comment by lefthandedgoat** [comment]
Oh I think I pointed at the wrong file in that other ticket.  Try this and see if it works correct:

```
https://lefthandedgoat.github.io/canopy/reporttemplatep.html
```

**Comment by dvaston** [comment]
Thanks Chris, that worked, really appreciate the fast response :)
