### ISSUE TITLE
'enabled' assertion and text insertion issues

### ISSUE THREAD

**Issue by teknikal-wizard** [lefthandedgoat/canopy#523]
Hi there,

I'm just updating some of our SAFE stack course modules, and I am finding some issues with canopy.

I have a button that is enabled when a text box has content, and disabled when it is empty.

I tried to write a simple test for this and it wasn't working.

I found that
1. The `enabled` / `disabled` assertions were failing as the button is reported as `notDisplayed` when disabled, causing a timeout.
2. Emptying the text box programmatically does not trigger the `onChanged` event so the button remains active, however adding text *does* trigger it)

I have attached a sample showing these cases.

Use `dotnet run` in the root for the main app 
[app.zip](https://github.com/lefthandedgoat/canopy/files/7295454/app.zip)

**Comment by lefthandedgoat** [comment]
I get this:
```
../app/Build.fsproj(10,3): error MSB4019: The imported project "../app/.paket/Paket.Restore.targets" was not found. Confirm that the expression in the Import declaration ".paket/Paket.Restore.targets" is correct, and that the file exists on disk.
```

If you can just give me a snippet of the line that is failing and then a snippet of the html for the control you are trying to test that would probably work.

**Comment by isaacabraham** [comment]
@Ryan-Palmer-CIT you'd be better off making a repository and committing to there rather than a zip TBH.
