### ISSUE TITLE
Could not load type 'OpenQA.Selenium.PhantomJS.PhantomJSDriverService'

### ISSUE THREAD

**Issue by JeremiahWCRI** [lefthandedgoat/canopy#525]
**Describe the bug**
I cannot run a project using canopy via paket. I started the project as a nuget project and opened canopy.classic where necessary. Migrated the project to paket and the compiler yells at me for canopy.classic. So, I remove the .classic bit and it compiles. But, when I go to start a chrome instance I get the following error: 

```
System.TypeLoadException: 'Could not load type 'OpenQA.Selenium.PhantomJS.PhantomJSDriverService' from assembly 'WebDriver, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'.'
```
**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 96

**Comment by lefthandedgoat** [comment]
It looks like you are pointing at Selenium 4, canopy is built against selenium 3, try version 3.141.0

**Comment by JeremiahWCRI** [comment]
That was it. Thank you.
