### ISSUE TITLE
OpenQA.Selenium.Chrome.ChromeDriverService.set_WhitelistedIPAddresses(System.String) error message

### ISSUE THREAD

**Issue by mikej0** [lefthandedgoat/canopy#530]
**Describe the bug**
Hi,

Working on some tests, and had to update Selenium ChromeDriver. While I was at it I also updated Selenium.Support and Selenium.WebDriver in my project too. (Both went from v4.16.2 to 4.18.1.)

I now get the error: 

System.MissingMethodException: 'Method not found: 'Void OpenQA.Selenium.Chrome.ChromeDriverService.set_WhitelistedIPAddresses(System.String)'.'

Undoing the updates for Support and WebDriver gets things working again.

**To Reproduce**
1. Update Selenium.Support and Selenium.WebDriver to 4.18.1
2. Try running a test - it'll fail when it tries starting the browser.

**Expected behavior**
Tests should run

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, but probably any browser.
 - Version 122

**Additional context**

**Comment by lefthandedgoat** [comment]
This looks like a breaking change in Selenium 4.18 that was unintended.  

https://github.com/SeleniumHQ/selenium/pull/13626

For now you can use 4.17 and wait for this bufix to be released in 4.18.?

**Comment by mikej0** [comment]
Hello,

Thanks for spotting that - yep, I can wait. I'd assumed the change was intentional. Although, I guess if the original property has been marked obsolete, it's only a matter of time before this'll crop up again.

Now I know.

Thanks
